const fs = require('fs');
const path = require('path');

// 27 reviews from the prompt
const promptReviews = [
  {
    reviewer_name: 'Edgars Dzirkalis',
    reviewer_job_title: 'Accounting Manager',
    reviewer_company: 'Dzirkalis & Associates',
    reviewer_industry: 'Accounting',
    reviewer_company_size: '51-200',
    reviewer_country: 'South Africa',
    verified_linkedin: true,
    verified_badge: 'Verified LinkedIn User',
    used_for_duration: '2+ years',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 4,
    functionality: 4,
    review_title: 'Well known product but has great user interface and allows flexibility to customize it',
    summary: 'Well known product but has great user interface and allows flexibility to customize it.',
    pros: 'The software allows plenty of flexibility to customize layout and invoicing fields. Navigation is smooth and user interface is well structured.',
    cons: 'For very small teams it can feel a bit feature-heavy at start, but once set up it works well.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-05-15',
    helpful_count: 5
  },
  {
    reviewer_name: 'Robert Evans',
    reviewer_job_title: 'Director',
    reviewer_company: 'Evans Logistics',
    reviewer_industry: 'Logistics and Supply Chain',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '1-2 years',
    overall_rating: 1,
    ease_of_use: 2,
    value_for_money: 1,
    customer_service: 2,
    functionality: 1,
    review_title: 'The software is old-fashioned and filled with bugs',
    summary: 'The software is old-fashioned and filled with bugs, for example, when you select all transactions on a page it will then go and change ALL transactions in your directory - which can take hours to manually fix. When batch editing the attachments also freeze and you have to reset the entire page each time.',
    pros: 'Basic navigation is okay but is overshadowed by frustrating bugs.',
    cons: 'Selecting all transactions on a page changes all transactions in your directory. Attachment freezing during batch editing requires constant resets.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-05-18',
    helpful_count: 24
  },
  {
    reviewer_name: 'Stan K.',
    reviewer_job_title: 'Owner',
    reviewer_company: 'E-Learning Academy',
    reviewer_industry: 'E-Learning',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '2+ years',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 5,
    customer_service: 5,
    functionality: 5,
    review_title: 'Easy and Accessible',
    summary: 'Not sure - nothing springs to mind as we engage',
    pros: 'Ease of use Not sure - nothing springs to mind as we engage',
    cons: 'Not sure - nothing springs to mind as we engage',
    vendor_response: "Thank you for your review, Stan. We're pleased that Sage Accounting has been a good choice for your e-learning business. I would like to invite you to join our customer advocacy program to connect more on your experience. Plus, you can access exclusive events, content and unlock Sage rewards. Please use this link: https://en.sagechampions.com/join/Gartner to join! Thanks, Bethany McDermott, Sage Customer Marketing Manager - Reviews",
    vendor_response_date: '2024-08-08',
    review_date: '2024-04-29',
    helpful_count: 12
  },
  {
    reviewer_name: 'Lise F.',
    reviewer_job_title: 'Secretary and treasurer',
    reviewer_company: 'Sports Club Association',
    reviewer_industry: 'Sports',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '2+ years',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 4,
    customer_service: 5,
    functionality: 5,
    review_title: 'Evaluation',
    summary: 'I used to work in administration and the whole accounting for a large Non-profit and used it for over 20 years. It was then called Simply accounting.',
    pros: 'The customer support and the facility to u8se the product are very good. Actually all opf the topics to choose fromn are easy to understand and used.',
    cons: "The only thing is that it is a very expansive product and not available to everyone. I'm retired and I do work on a volunteer base for a small and new non-profit organisation and responsible to a board of directors, they feeled that it was too expansive, the only version available at a decent price is the online version but being from the old school I do not like to use the online.",
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-04-27',
    helpful_count: 3
  },
  {
    reviewer_name: 'Blanka D.',
    reviewer_job_title: 'Owner',
    reviewer_company: 'Accounting Studio',
    reviewer_industry: 'Accounting',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: true,
    verified_badge: 'Verified LinkedIn User',
    used_for_duration: '2+ years',
    overall_rating: 2,
    ease_of_use: 2,
    value_for_money: 2,
    customer_service: 2,
    functionality: 3,
    review_title: 'Not to impressed with 10+ years of Sage Accounting',
    summary: 'Overall, the customer support is disappointing and often unhelpful. The platform is not very intuitive and can be difficult to navigate, especially for clients who are not familiar with accounting software. Payroll not being built into the system adds unnecessary complexity and results in additional costs, making workflows less efficient. The reconciliation process could be significantly improved, and both invoicing and expense tracking lack the level of efficiency and automation that is now standard in many competing tools. While Sage does market AI capabilities, they are not meaningfully integrated into the core user experience of Sage Business Cloud Accounting. In practice, many everyday workflows still feel manual and lack the level of intelligent automation now expected in modern accounting software.',
    pros: 'While I didn’t personally find the platform to offer strong value for money, I’ve worked with it extensively because many of my clients use it. The financial reporting is adequate and gets the job done; however, it feels limited when compared to other platforms like QuickBooks Online. The range of reporting options and the level of customization available there allow users to tailor reports far more effectively and extract more meaningful insights.',
    cons: 'Due to limited integrations, I eventually transitioned most of my clients from Sage Business Cloud Accounting to QuickBooks Online. A key example is payroll—since it is not natively built into the platform, it requires additional tools, leading to added costs, inefficiencies, and a more fragmented workflow.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-04-30',
    helpful_count: 14
  },
  {
    reviewer_name: 'Vincent S.',
    reviewer_job_title: 'Owner, Consultant and Accountant',
    reviewer_company: 'VS Advisory Services',
    reviewer_industry: 'Accounting',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: true,
    verified_badge: 'Verified LinkedIn User',
    used_for_duration: '2+ years',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 3,
    customer_service: 4,
    functionality: 4,
    review_title: 'Bedford, Simply Accounting then Sage Accounting',
    summary: 'I have bee using this evolving accounting software since 1981. It has evolved into Simply Accounting and then Sage Accounting. in the 80\'s and 90\'s we used to pay between $200.00 to $500.00 yearly and had more for our money then today, you even owned your license. Nowadays it has been converted to subscription type, charge our clients thousands of dollars. and if you cancel your subscription, you can no longer use the software, not even adjust all entries. These days our clients pay thousands of dollars without even owning their licenses. There must be still some other software that allow you to have control over your license. This is insight contemplating to seek other solutions. Shame that in 2026, technologically we may be advanced, however ethically I have my concerns. I still value integrity and recommend to my clients not to fall in the trap of technology, but instead consider their needs.',
    pros: 'I find Sage accounting to be one of the most user friendly for all types of users. I consider it 95% complete. Which in my opinion excellent. No software solution in the market is genuine 100% complete. There will always be something missing.',
    cons: 'For Offline users it has become one of the worst. I do not recommend it 100% for offline users. It has become extremely expensive.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-03-24',
    helpful_count: 11
  },
  {
    reviewer_name: 'Dylan W.',
    reviewer_job_title: 'Owner',
    reviewer_company: 'Dylan Retail Store',
    reviewer_industry: 'Retail',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '2+ years',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 4,
    customer_service: 5,
    functionality: 5,
    review_title: 'Recommended Product',
    summary: 'A good all in one software to help organize and manage my business. The ease of invoicing and receiving payments is one of the best additional features.',
    pros: 'Sage has all the features I need to organize my business expenses and handle invoicing and inventory.',
    cons: 'The pricing is a bit on the expensive side for a small business. I don’t need all the functionality it provides.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-04-27',
    helpful_count: 8
  },
  {
    reviewer_name: 'Évelyne F.',
    reviewer_job_title: 'Adjointe administrative',
    reviewer_company: 'NPO Hub',
    reviewer_industry: 'Non-Profit Organization Management',
    reviewer_company_size: '11-50',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '2+ years',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 5,
    customer_service: 5,
    functionality: 5,
    review_title: 'Userfriendly, i recommand it !',
    summary: "I use it every month for work and even recommand it to an other non-profit organisation to help them with their finances. It's a time saver and really easy to use !",
    pros: "Extremely clean interface, saves time, reports are generated instantly.",
    cons: "No major issues, works beautifully for our NGO requirements.",
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-04-21',
    helpful_count: 6
  },
  {
    reviewer_name: 'Jacki N.',
    reviewer_job_title: 'Bookkeeper',
    reviewer_company: 'HR Services South Africa',
    reviewer_industry: 'Human Resources',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: 'Less than 6 months',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 4,
    customer_service: 4,
    functionality: 4,
    review_title: 'Happy With Moving to Sage Accounting',
    summary: 'I do like having a cloud based service and the onboarding was helpful. [sensitive content hidden] was great and helped answer a lot of questions even now, months later.',
    pros: 'I liked the intuitive nature of the program and auto integration of being able to issue invoices and collect payments automatically.',
    cons: "I can't upload our bank feed as it's from a credit union. I'm not a huge fan of the bank rec process. I'd also like the ability to create custom reports.",
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-04-22',
    helpful_count: 7
  },
  {
    reviewer_name: 'Ben F.',
    reviewer_job_title: 'Owner coach trainer',
    reviewer_company: 'Fitness and Sports Academy',
    reviewer_industry: 'Sports',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '1-2 years',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 4,
    functionality: 4,
    review_title: 'Accounting made easy',
    summary: 'Very positive in terms of time management and access to timely reports that allow for improve coordination',
    pros: 'Find a software easy to use access to videos for tutorials is made easy and just the simplification of having reporting',
    cons: 'Just the mundane business of receipts & data entry lol i’m hoping to find a scanning feature that helps this process',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-04-27',
    helpful_count: 4
  },
  {
    reviewer_name: 'Carol H.',
    reviewer_job_title: 'Owner',
    reviewer_company: 'Carol Boutique',
    reviewer_industry: 'Retail',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: 'Less than 6 months',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 5,
    customer_service: 5,
    functionality: 4,
    review_title: 'Newbie loving it',
    summary: 'Im new learning books on my own and its pretty easy once you get started. I was terrified to start but im almost done 2025 and i feel better. So sage helped me i did try quick books nope not for me.',
    pros: 'The ease of the program I like using Sage because it keeps my bookkeeping simple, organized, and easy to manage. Instead of overcomplicating things, I can enter my transactions in a way that makes sense for how I actually run my business. I prefer working with monthly totals rather than hundreds of small entries, and Sage allows me to do that while still keeping everything accurate.',
    cons: 'Cant think of anything so far as i am still learning as of now im happy with it and the help links make it even better. Maybe add a chat to some thinks to help walk through would help more',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-04-21',
    helpful_count: 9
  },
  {
    reviewer_name: 'LESLEY V.',
    reviewer_job_title: 'Accountant',
    reviewer_company: 'LV Bookkeeping',
    reviewer_industry: 'Accounting',
    reviewer_company_size: '11-50',
    reviewer_country: 'South Africa',
    verified_linkedin: true,
    verified_badge: 'Verified LinkedIn User',
    used_for_duration: '2+ years',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 5,
    customer_service: 5,
    functionality: 5,
    review_title: "Sage Accounting is second to none - Don't go anywhere else.",
    summary: 'Sage Accounting helps me get through the tasks of the day easily and quickly. The updates always change something for the better and any problems I have I know I can just ring up Sage and their knowledgable support staff can guide me through things or log in and sort it out extremely quickly.',
    pros: "I've used Sage Accounting for 15 years and the software is second to none. The screens are easy to navigate, the reports are easily managed and amended to suit the client, it saves time with inputting when you can memorise a screen for future use. The customer support is exceptionally good. It enables me to log in and look at my clients accounts without having to visit their offices which in itself is time saving as I can spot any errors quickly and readjust where necesary or talk them through how to correct it.",
    cons: 'There is nothing I dislike about Sage Accounting. The design, the navigation and the ease of use has kept me using Sage Accounting for 15 years. I wouldn\'t go anywhere else.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-04-24',
    helpful_count: 15
  },
  {
    reviewer_name: 'Valerie M.',
    reviewer_job_title: 'Accountant',
    reviewer_company: 'Valerie Consulting Services',
    reviewer_industry: 'Accounting',
    reviewer_company_size: '11-50',
    reviewer_country: 'South Africa',
    verified_linkedin: true,
    verified_badge: 'Verified LinkedIn User',
    used_for_duration: '2+ years',
    overall_rating: 4,
    ease_of_use: 3,
    value_for_money: 3,
    customer_service: 4,
    functionality: 4,
    review_title: 'Sage50 versus Sage Cloud (not very innovative)',
    summary: 'I am a loyal and faithful person. I hope these fixes will be implemented quickly and that the product will be more competitive with QuickBooks and others.',
    pros: 'I have been using Sage 50 for over 15 years and I have always found this product very easy to use, fast in execution, with many reporting possibilities, very professional software and without bugs....But my enthusiasm flew away when I switched to Sage Cloud.',
    cons: 'For the past two years, I\'ve migrated all my clients to Sage Cloud, thinking I was taking a step forward. But honestly, I regret my move. I feel like I\'m going backward when it should be even faster and more efficient than Sage 50. And my clients aren\'t very happy either. For example, one of my clients has five companies but manages everything under a single email address. However, it takes a different email address to open a new company, which I find ridiculous. Secondly, the project-based accounting isn\'t very advanced. I can\'t generate a single report with all the projects included. If I have 15 projects, I have to generate 15 separate reports. This will be nonsensical by 2026. The same goes for manually transferring GL balances to the net profit at the end of the year. This should be done automatically. These are just a few of the irritations I encounter on a daily basis.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-01-20',
    helpful_count: 18
  },
  {
    reviewer_name: 'Allen S.',
    reviewer_job_title: 'Chief Financial Officer',
    reviewer_company: 'HR Capital Group',
    reviewer_industry: 'Human Resources',
    reviewer_company_size: '51-200',
    reviewer_country: 'South Africa',
    verified_linkedin: true,
    verified_badge: 'Verified LinkedIn User',
    used_for_duration: '6-12 months',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 5,
    customer_service: 5,
    functionality: 5,
    review_title: 'The Easiest Accounting Experience I’ve Ever Had',
    summary: 'I can’t believe how much this has improved my day‑to‑day work! It’s incredibly easy to use and makes running my small business feel effortless. I actually enjoy using it—highly recommended!',
    pros: 'What stands out most is how straightforward the whole platform is. Bank reconciliation is effortless, and the reporting tools are ready to use right away, which saves a ton of time. The invoicing section is clean and easy, and the transaction‑matching feature does a great job preventing any double‑ups. It feels built with real‑world small business workflows in mind.',
    cons: 'My only real struggle has been handling irregular transactions such as bank‑reversed payments. The system works great overall, but these cases could be more intuitive.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-01-20',
    helpful_count: 10
  },
  {
    reviewer_name: 'Jennae H.',
    reviewer_job_title: 'Administrator',
    reviewer_company: 'Cape Town Construction Ltd',
    reviewer_industry: 'Construction',
    reviewer_company_size: '11-50',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '1-2 years',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 5,
    customer_service: 1,
    functionality: 4,
    review_title: 'Great to use!',
    summary: "I really enjoy it! It's easier to use and the cost is great! I can easily report my finances and invoicing is a breeze.",
    pros: 'Its really easy to send invoices and you can see when the invoice was delevered and when it was seen. This way I know when my customers get my invoices.',
    cons: 'Trying to get a hold of customer service is a nightmare. I have had issues in the past and really needed to speak to someone and it was really hard to find any phone numbers or any contact info to help. I neded up figuring things out on my own but it took longer and was not easy to do.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2025-09-19',
    helpful_count: 13
  },
  {
    reviewer_name: 'Shane C.',
    reviewer_job_title: 'Locksmith',
    reviewer_company: 'Shane Security & Automotive',
    reviewer_industry: 'Automotive',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '6-12 months',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 5,
    customer_service: 3,
    functionality: 3,
    review_title: 'Mostly satisfied - could use a few more features',
    summary: "For the most part Sage is an excellent product, but it could do with some improvements, things that would make me want to recommend this product to others, but Quickbooks has features that Sage doesn't that made things run a bit smoother overall. However your price is very agreeable for our small business",
    pros: 'I like how easy it is to organize invoices, products and match banking records. The front page gives me a full view of of ingoing and outgoing expenses, I can see who still owes on invoices.',
    cons: "I would love to see a rearrange lines in an estimate or a quote, I think that is a very big oversight, something I miss from using Quickbooks. The help pages don't work on my browser (Chrome) which I think is pretty frustrating overall. I have noticed that the product filter doesn\'t work very well, something else that I find frustrating when I am trying to work in sections of inventory.",
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2025-12-18',
    helpful_count: 8
  },
  {
    reviewer_name: 'Aaron R.',
    reviewer_job_title: 'Certified Professional Bookkeeper',
    reviewer_company: 'Precision Bookkeeping',
    reviewer_industry: 'Accounting',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '1-2 years',
    overall_rating: 2,
    ease_of_use: 3,
    value_for_money: 2,
    customer_service: 3,
    functionality: 2,
    review_title: 'Give us the functionality we ask for!',
    summary: "Honestly, wish you'd find a way to take Sage 50 and just make it cloud based. I love Sage 50. Sage Accounting is far too limited in functionality. It's leagues behind Xero and QBO - I hate QBO personally.",
    pros: 'I like that my customers can do their own invoicing through Sage Accounting & I can pull the data in to Sage 50.',
    cons: 'The inability to give multiple users permissions to use the app. The inability to adjust tax codes for my own use. The inability to issue receipts - come on - why is this still an issue? Should have been included with the first release and we\'ve been asking for this functionality forever. The inability to adjust invoices beyond the templates. Limited apps for integration.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2025-11-04',
    helpful_count: 22
  },
  {
    reviewer_name: 'Chantal H.',
    reviewer_job_title: 'Accounting clerk',
    reviewer_company: 'Prime Consumer Services',
    reviewer_industry: 'Consumer Services',
    reviewer_company_size: '11-50',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '6-12 months',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 4,
    functionality: 4,
    review_title: 'Easy and reliable',
    summary: 'So far I am happy with the overall experience and I will be more able to comment after at least one full year of using it.',
    pros: 'It is quite easy to use and has many functions that make the daily and monthly tasks easier. So far I enjoy working with Sage.',
    cons: 'The invoice models are very limited and also the layout and information that can be added. If proportional payments would be offered, it would also be something I would use.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2025-12-02',
    helpful_count: 5
  },
  {
    reviewer_name: 'Sandi C.',
    reviewer_job_title: 'Owner',
    reviewer_company: 'Sandi Fine Furniture',
    reviewer_industry: 'Furniture',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '2+ years',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 4,
    functionality: 4,
    review_title: 'Sage - Option',
    summary: "Good but I haven't had to use to much of the help options, except for payroll, so I am not sure how well that will work if needed.",
    pros: 'Simple to use and convenient if you need to make an adjustment. Compared to older versions of Sage this is easier to navigate.',
    cons: "Payroll. I believe all the steps needed when to enter hourly employees bi-weekly hours is a little to many steps and double checks needed. You do get used to it, but it's to many steps every time.",
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2025-12-02',
    helpful_count: 3
  },
  {
    reviewer_name: 'Connie B.',
    reviewer_job_title: 'Owner',
    reviewer_company: 'Ongoing Living & Learning Inc.',
    reviewer_industry: 'Civic & Social Organization',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '2+ years',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 5,
    customer_service: 4,
    functionality: 4,
    review_title: 'Ongoing Living & Learning Inc.',
    summary: 'Good. I also use Sage Intaact for my larger business. I find Sage perfect for the smaller side business - just enough accounting capabilities to not be confusing.',
    pros: 'Ease of use and learning tools. The invoicing tool works well for what I am using. We are a charity and appreciate the discounted fees very much.',
    cons: 'It keeps dropping my bank feed. I found the bank reconciliation a bit difficult with the dates. Do not like that if you approve a bank transaction in the banking feed past the end of the month when you do the reconciliation ending prior it will not allow it.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2025-12-08',
    helpful_count: 6
  },
  {
    reviewer_name: 'Pierre-Marie D.',
    reviewer_job_title: 'President',
    reviewer_company: 'PMD Civil Engineering',
    reviewer_industry: 'Civil Engineering',
    reviewer_company_size: '11-50',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '1-2 years',
    overall_rating: 2,
    ease_of_use: 3,
    value_for_money: 2,
    customer_service: 1,
    functionality: 2,
    review_title: 'Pretty bad',
    summary: 'not very good, the product is very expensive for the fonctionality , i am keeping it just because migrating is a pain in the ...',
    pros: 'Relatively easy to use. not much else noce to say about it , I have to keep typing so i can press next.',
    cons: 'the customer service is really bad. the conectivity with the bank is always difficult. Some operations are tedious',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-03-12',
    helpful_count: 19
  },
  {
    reviewer_name: 'Michelle C.',
    reviewer_job_title: 'Owner',
    reviewer_company: 'Wellness & Fitness Studio',
    reviewer_industry: 'Health, Wellness and Fitness',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '6-12 months',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 2,
    functionality: 3,
    review_title: 'Mediocre: Does the basics. Could be more efficient',
    summary: "Ease of use but I'm wasting a lot of time uploading my bank transactions. I've tried reaching out on the chat multiple times and no one knows how to help me.",
    pros: 'I like the ease of use of Sage. It is very user friendly and provides reporting at a quick glance for me to see how my business is performing. Also makes my accounting easier.',
    cons: "Slow. My bank transactions don't upload automatically. I can connect my bank and then I have to manually load every transaction.",
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-01-21',
    helpful_count: 12
  },
  {
    reviewer_name: 'Erika H.',
    reviewer_job_title: 'Business Owner',
    reviewer_company: 'Erika Retail Outlets',
    reviewer_industry: 'Retail',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '1-2 years',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 2,
    functionality: 4,
    review_title: 'To Sage or not to Sage online!',
    summary: 'Overall, switching to Sage online was an important part of the puzzle for me to transition into retirement.',
    pros: 'I appreciate that I can work from anywhere! I also love that my assistant and I can both work on Sage simultaneously and network from different locations.',
    cons: 'Customer service is the most difficult part of Sage. It is almost impossible to chat live with a human to figure out a problem.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2025-12-12',
    helpful_count: 11
  },
  {
    reviewer_name: 'Liza T.',
    reviewer_job_title: 'Owner Operator',
    reviewer_company: 'LT Construction & Civils',
    reviewer_industry: 'Construction',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '2+ years',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 4,
    functionality: 4,
    review_title: 'Reliable and straight forward',
    summary: 'Overall it is the best system I have used. I have been using Simply Accounting for over 20 year. I love that you can customize the system to suit your business needs.',
    pros: 'I have been using Simply Accounting for over 20 years. I love the simplicity of the system and how more in depth you can use it if you need to. Almost 2 years ago I changed from Sage 50 to the Sage one online system. It took some getting used to but I love I can work anywhere that has internet.',
    cons: 'I don\'t like that you can\'t search customers by address or ph #. On the Sage One I miss having the capabilities of memorized transactions',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2025-12-09',
    helpful_count: 7
  },
  {
    reviewer_name: 'Paul L.',
    reviewer_job_title: 'Co-owner',
    reviewer_company: 'Durban Food & Beverages',
    reviewer_industry: 'Food & Beverages',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '2+ years',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 4,
    functionality: 4,
    review_title: 'Easy to use and very useful!',
    summary: 'Pleased with features and easy to use for invoicing. Helps us see where things are at, at any given time.',
    pros: 'One-stop shop for our business finances. Features and setup are practical. Easy to navigate and work with.',
    cons: 'Having only one person able to receive a code for logging in. Two of us use the account and when one gets logged out, the other has to get a code to log in. Only one person is able to get the code.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-03-17',
    helpful_count: 5
  },
  {
    reviewer_name: 'Jayden L.',
    reviewer_job_title: 'VP of Accounting',
    reviewer_company: 'Jayden Projects Group',
    reviewer_industry: 'Construction',
    reviewer_company_size: '51-200',
    reviewer_country: 'South Africa',
    verified_linkedin: true,
    verified_badge: 'Verified LinkedIn User',
    used_for_duration: '2+ years',
    overall_rating: 5,
    ease_of_use: 5,
    value_for_money: 5,
    customer_service: 5,
    functionality: 5,
    review_title: "SAGE 10/10 AMAZING CAN'T LIVE WITHOUT IT",
    summary: "10/10 super easy to use and has a lot of great features to help me get what i need done. Whether it's payables, receivables or reporting Sage is a platform that can do it all!",
    pros: 'Sage is an amazing product! Super easy to use both and easy to get customer support. We are a medium sized business, but this is perfect from all business ranging from small to conglomerates due to how easy it is to access and its value for money. The way that sage displays its data make it super easy for financial reporting. It is great for invoicing as well due to how well it displays data',
    cons: 'It is not a software you can learn within a day, however once you get the hang of it Sage is an irreplaceable tool!',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-03-13',
    helpful_count: 14
  },
  {
    reviewer_name: 'Mia D.',
    reviewer_job_title: 'Managing Director',
    reviewer_company: 'Mia D. Photography',
    reviewer_industry: 'Photography',
    reviewer_company_size: '2-10',
    reviewer_country: 'South Africa',
    verified_linkedin: false,
    verified_badge: null,
    used_for_duration: '1-2 years',
    overall_rating: 4,
    ease_of_use: 4,
    value_for_money: 4,
    customer_service: 3,
    functionality: 4,
    review_title: 'Sage cloud',
    summary: 'I was paying way too much for what I needed for years! Every year when renewing I would ask if there was a way to lower my subscription. The answer would be no. Last year however I insisted so much that I was prompted to a sage cloud, much cheaper and all that I needed. I resent that Sage kept this from me for years and made me pay a big bill for a system that I didn\'t need.',
    pros: 'The new cloud system is intuitive and easy to use. I am much happier using the cloud, especially because it\'s saving me money I didn\'t need to spend to begin with.',
    cons: 'Poor customer service. I was not informed of less expensive possibilities that would have helped me save money.',
    vendor_response: null,
    vendor_response_date: null,
    review_date: '2026-05-23',
    helpful_count: 9
  }
];

// Seed lists to generate 83 high-fidelity reviews to make 110 reviews in total
const firstNames = ['Sipho', 'Kelebogile', 'Johan', 'Zanele', 'Jacques', 'Lerato', 'Tshepo', 'Naledi', 'Pieter', 'Kgomotso', 'Andries', 'Fatima', 'Bongani', 'Chantel', 'Ruan', 'Nomsa', 'Willem', 'Thabo', 'Kirsten', 'Ebrahim', 'Precious', 'Hendrik', 'Mbali', 'David', 'Nkosana', 'Melanie', 'Gareth', 'Lindiwe', 'Riaan', 'Priya', 'Craig', 'Dineo', 'Francois', 'Hlengiwe', 'Wayne', 'Themba', 'Charmaine', 'Devon', 'Nthabiseng', 'Hein', 'Aisha', 'Zuki', 'Stefan', 'Lungile', 'Nicole', 'Gideon', 'Liezel', 'Xolani', 'Anneri', 'Mark', 'Palesa', 'Justin', 'Saray', 'Gary', 'Mthokozisi', 'Rene', 'Tebogo', 'Werner', 'Boipelo', 'Kobus'];
const lastNames = ['Mokoena', 'van der Merwe', 'Naidoo', 'Khumalo', 'Botha', 'Smit', 'Zulu', 'Nkabinde', 'Pillay', 'Louw', 'Dlamini', 'Ndlovu', 'Pretorius', 'Govender', 'Burger', 'Molefe', 'Viljoen', 'Modise', 'Nkosi', 'Marais', 'Du Plessis', 'Bester', 'Jansen', 'Moosa', 'Coetzee', 'Zondo', 'Mabaso', 'Swanepoel', 'Kruger', 'Fourie', 'Grootboom', 'Masinga', 'Venter', 'Tshabalala', 'Appelgryn', 'Mthembu', 'Olivier', 'Bekker', 'Theron', 'Sithole'];

const jobs = [
  'Owner', 'Founder', 'Managing Director', 'Financial Manager', 'Senior Bookkeeper',
  'Chartered Accountant', 'Finance Director', 'Business Administrator', 'Operations Manager', 'CFO',
  'General Manager', 'Finance Clerk', 'Tax Practitioner', 'Practice Manager', 'Partner'
];

const companies = [
  'Trading Enterprise', 'Consulting Group', 'Boutique Service', 'Logistics SA', 'Creative Studio',
  'Construction Services', 'Retail Holdings', 'Tech Solutions', 'Engineering Partners', 'Distribution Ltd',
  'Property Group', 'Tourism & Travel', 'Security Services', 'Food Distributors', 'Auto Repairs'
];

const industries = [
  'Retail', 'Wholesale', 'Manufacturing', 'Construction', 'Consulting', 'Professional Services',
  'Hospitality', 'Real Estate', 'Logistics', 'Healthcare', 'Agriculture', 'Education', 'IT Services',
  'Non-Profit Organization Management', 'Engineering'
];

const sizes = ['1-10', '11-50', '51-200', '201-500'];
const durations = ['Less than 6 months', '6-12 months', '1-2 years', '2+ years'];

const prosList = [
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'User interface is clean and straightforward. Easy for non-accounting staff to invoice clients.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Audit trail compliance is robust and keeps our financial history highly transparent.',
  'Simple and clean invoice templates that look highly professional.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Great value for money compared to expensive offline ERP systems.',
  'Being cloud-based allows me to check reports on the go from anywhere in South Africa.'
];

const consList = [
  'Occasional bank feed drops that require manual reconciliation or re-authentication.',
  'Pricing increases yearly, making it harder for very small businesses to justify.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  'Lack of native payroll integration means we have to pay extra for third-party tools.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  'Manual GL adjustments at year-end are required instead of being fully automated.',
  'Project-based tracking is tedious to set up and report on separately.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  'Some batch editing functions freeze or load slowly when internet connection drops.'
];

const titles = [
  'Reliable cloud accounting for SA SMBs',
  'Fantastic VAT201 handling',
  'Decent product but support can improve',
  'Easy invoicing and bank feeds',
  'A solid upgrade from spreadsheets',
  'Highly recommended for small practices',
  'Good value but pricing is creeping up',
  'Intuitive layout, simple to navigate',
  'Good features but some bugs exist',
  'The industry standard for a reason'
];

const summaries = [
  'We have been using Sage for our accounting needs and it has made reporting and VAT compliance straightforward. The bank feeds save a lot of manual input.',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'Solid accounting software. The bank feeds and invoicing features are excellent, but payroll missing natively is a downside.',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'Good value for money. Very compliant with SARS requirements, though project accounting needs improvement.'
];

// Helper to get random item
function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Generate the remaining reviews (83 to reach 110 total)
const generatedReviews = [];
const startDate = new Date('2025-01-01').getTime();
const endDate = new Date('2026-06-01').getTime();

for (let i = 0; i < 83; i++) {
  const fName = getRandom(firstNames);
  const lName = getRandom(lastNames);
  const name = `${fName} ${lName[0]}.`;
  const rating = Math.random() > 0.3 ? (Math.random() > 0.4 ? 5 : 4) : (Math.random() > 0.3 ? 3 : 2);
  const ease = Math.min(5, Math.max(1, rating + (Math.random() > 0.5 ? 0 : (Math.random() > 0.5 ? 1 : -1))));
  const value = Math.min(5, Math.max(1, rating + (Math.random() > 0.5 ? 0 : (Math.random() > 0.5 ? 1 : -1))));
  const service = Math.min(5, Math.max(1, rating - (Math.random() > 0.7 ? 1 : 0)));
  const func = Math.min(5, Math.max(1, rating + (Math.random() > 0.6 ? 0 : (Math.random() > 0.5 ? 1 : -1))));
  
  // Date in YYYY-MM-DD format
  const randTime = startDate + Math.random() * (endDate - startDate);
  const dateStr = new Date(randTime).toISOString().split('T')[0];

  const industry = getRandom(industries);
  const company = `${getRandom(companies)} ${getRandom(['', 'Holdings', 'Pty Ltd', 'Group']).trim()}`.trim();

  generatedReviews.push({
    reviewer_name: name,
    reviewer_job_title: getRandom(jobs),
    reviewer_company: company,
    reviewer_industry: industry,
    reviewer_company_size: getRandom(sizes),
    reviewer_country: 'South Africa',
    verified_linkedin: Math.random() > 0.5,
    verified_badge: Math.random() > 0.5 ? 'Verified LinkedIn User' : null,
    used_for_duration: getRandom(durations),
    overall_rating: rating,
    ease_of_use: ease,
    value_for_money: value,
    customer_service: service,
    functionality: func,
    review_title: getRandom(titles),
    summary: getRandom(summaries),
    pros: getRandom(prosList),
    cons: getRandom(consList),
    vendor_response: null,
    vendor_response_date: null,
    review_date: dateStr,
    helpful_count: Math.floor(Math.random() * 10)
  });
}

// Compile all reviews
const allReviews = [...promptReviews, ...generatedReviews];

// Helper to escape SQL single quotes
function escapeSql(str) {
  if (str === null || str === undefined) return 'NULL';
  return `'${str.replace(/'/g, "''")}'`;
}

// Build SQL file content
let sqlContent = `-- ============================================================================
-- SQL Seed File for Sage Accounting Reviews (110 Total Reviews)
-- Dynamically targets the software ID using a subquery based on the slug 'sage-accounting'.
-- Deletes any existing reviews for this software to prevent duplicates/placeholders.
-- ============================================================================

-- Start Transaction
BEGIN;

-- Resolve the software ID and clean up any current reviews for Sage Accounting
DELETE FROM reviews WHERE software_id = (SELECT id FROM software WHERE slug = 'sage-accounting');

-- Insert 110 reviews (27 real, 83 realistic mock reviews)
INSERT INTO reviews (
  software_id,
  reviewer_name,
  reviewer_job_title,
  reviewer_company,
  reviewer_industry,
  reviewer_company_size,
  reviewer_country,
  verified_linkedin,
  verified_badge,
  used_for_duration,
  overall_rating,
  ease_of_use,
  value_for_money,
  customer_service,
  functionality,
  review_title,
  summary,
  pros,
  cons,
  vendor_response,
  vendor_response_date,
  review_date,
  helpful_count,
  status
) VALUES
`;

const valuesStrings = allReviews.map(r => {
  const verifiedBadge = r.verified_badge ? escapeSql(r.verified_badge) : 'NULL';
  const vendorResponse = r.vendor_response ? escapeSql(r.vendor_response) : 'NULL';
  const vendorResponseDate = r.vendor_response_date ? escapeSql(r.vendor_response_date) : 'NULL';
  
  return `(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  ${escapeSql(r.reviewer_name)},
  ${escapeSql(r.reviewer_job_title)},
  ${escapeSql(r.reviewer_company)},
  ${escapeSql(r.reviewer_industry)},
  ${escapeSql(r.reviewer_company_size)},
  ${escapeSql(r.reviewer_country)},
  ${r.verified_linkedin},
  ${verifiedBadge},
  ${escapeSql(r.used_for_duration)},
  ${r.overall_rating},
  ${r.ease_of_use},
  ${r.value_for_money},
  ${r.customer_service},
  ${r.functionality},
  ${escapeSql(r.review_title)},
  ${escapeSql(r.summary)},
  ${escapeSql(r.pros)},
  ${escapeSql(r.cons)},
  ${vendorResponse},
  ${vendorResponseDate},
  ${escapeSql(r.review_date)},
  ${r.helpful_count},
  'published'
)`;
});

sqlContent += valuesStrings.join(',\n') + ';\n\nCOMMIT;\n';

// Write the file
const targetPath = path.join(__dirname, 'insert_sage_reviews.sql');
fs.writeFileSync(targetPath, sqlContent, 'utf-8');
console.log(`Generated ${allReviews.length} reviews in insert_sage_reviews.sql!`);
