-- ============================================================================
-- SQL Seed File for Sage Accounting Reviews (110 Total Reviews)
-- Dynamically targets the software ID using a subquery based on the slug 'sage-accounting'.
-- Deletes any existing reviews for this software to prevent duplicates/placeholders.
-- ============================================================================

-- Start Transaction
BEGIN;

-- Resolve the software ID and clean up any current reviews for Sage Accounting
DELETE FROM reviews WHERE software_id = (SELECT id FROM software WHERE slug = 'sage-accounting');

-- Insert 110 reviews (27 real, 83 realistic mock reviews)
INSERT INTO reviews (
  software_id,
  reviewer_name,
  reviewer_job_title,
  reviewer_company,
  reviewer_industry,
  reviewer_company_size,
  reviewer_country,
  verified_linkedin,
  verified_badge,
  used_for_duration,
  overall_rating,
  ease_of_use,
  value_for_money,
  customer_service,
  functionality,
  review_title,
  summary,
  pros,
  cons,
  vendor_response,
  vendor_response_date,
  review_date,
  helpful_count,
  status
) VALUES
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Edgars Dzirkalis',
  'Accounting Manager',
  'Dzirkalis & Associates',
  'Accounting',
  '51-200',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  4,
  4,
  4,
  4,
  4,
  'Well known product but has great user interface and allows flexibility to customize it',
  'Well known product but has great user interface and allows flexibility to customize it.',
  'The software allows plenty of flexibility to customize layout and invoicing fields. Navigation is smooth and user interface is well structured.',
  'For very small teams it can feel a bit feature-heavy at start, but once set up it works well.',
  NULL,
  NULL,
  '2026-05-15',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Robert Evans',
  'Director',
  'Evans Logistics',
  'Logistics and Supply Chain',
  '2-10',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  1,
  2,
  1,
  2,
  1,
  'The software is old-fashioned and filled with bugs',
  'The software is old-fashioned and filled with bugs, for example, when you select all transactions on a page it will then go and change ALL transactions in your directory - which can take hours to manually fix. When batch editing the attachments also freeze and you have to reset the entire page each time.',
  'Basic navigation is okay but is overshadowed by frustrating bugs.',
  'Selecting all transactions on a page changes all transactions in your directory. Attachment freezing during batch editing requires constant resets.',
  NULL,
  NULL,
  '2026-05-18',
  24,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Stan K.',
  'Owner',
  'E-Learning Academy',
  'E-Learning',
  '2-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  5,
  5,
  5,
  5,
  5,
  'Easy and Accessible',
  'Not sure - nothing springs to mind as we engage',
  'Ease of use Not sure - nothing springs to mind as we engage',
  'Not sure - nothing springs to mind as we engage',
  'Thank you for your review, Stan. We''re pleased that Sage Accounting has been a good choice for your e-learning business. I would like to invite you to join our customer advocacy program to connect more on your experience. Plus, you can access exclusive events, content and unlock Sage rewards. Please use this link: https://en.sagechampions.com/join/Gartner to join! Thanks, Bethany McDermott, Sage Customer Marketing Manager - Reviews',
  '2024-08-08',
  '2024-04-29',
  12,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Lise F.',
  'Secretary and treasurer',
  'Sports Club Association',
  'Sports',
  '2-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  5,
  5,
  4,
  5,
  5,
  'Evaluation',
  'I used to work in administration and the whole accounting for a large Non-profit and used it for over 20 years. It was then called Simply accounting.',
  'The customer support and the facility to u8se the product are very good. Actually all opf the topics to choose fromn are easy to understand and used.',
  'The only thing is that it is a very expansive product and not available to everyone. I''m retired and I do work on a volunteer base for a small and new non-profit organisation and responsible to a board of directors, they feeled that it was too expansive, the only version available at a decent price is the online version but being from the old school I do not like to use the online.',
  NULL,
  NULL,
  '2026-04-27',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Blanka D.',
  'Owner',
  'Accounting Studio',
  'Accounting',
  '2-10',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  2,
  2,
  2,
  2,
  3,
  'Not to impressed with 10+ years of Sage Accounting',
  'Overall, the customer support is disappointing and often unhelpful. The platform is not very intuitive and can be difficult to navigate, especially for clients who are not familiar with accounting software. Payroll not being built into the system adds unnecessary complexity and results in additional costs, making workflows less efficient. The reconciliation process could be significantly improved, and both invoicing and expense tracking lack the level of efficiency and automation that is now standard in many competing tools. While Sage does market AI capabilities, they are not meaningfully integrated into the core user experience of Sage Business Cloud Accounting. In practice, many everyday workflows still feel manual and lack the level of intelligent automation now expected in modern accounting software.',
  'While I didn’t personally find the platform to offer strong value for money, I’ve worked with it extensively because many of my clients use it. The financial reporting is adequate and gets the job done; however, it feels limited when compared to other platforms like QuickBooks Online. The range of reporting options and the level of customization available there allow users to tailor reports far more effectively and extract more meaningful insights.',
  'Due to limited integrations, I eventually transitioned most of my clients from Sage Business Cloud Accounting to QuickBooks Online. A key example is payroll—since it is not natively built into the platform, it requires additional tools, leading to added costs, inefficiencies, and a more fragmented workflow.',
  NULL,
  NULL,
  '2026-04-30',
  14,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Vincent S.',
  'Owner, Consultant and Accountant',
  'VS Advisory Services',
  'Accounting',
  '2-10',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  4,
  4,
  3,
  4,
  4,
  'Bedford, Simply Accounting then Sage Accounting',
  'I have bee using this evolving accounting software since 1981. It has evolved into Simply Accounting and then Sage Accounting. in the 80''s and 90''s we used to pay between $200.00 to $500.00 yearly and had more for our money then today, you even owned your license. Nowadays it has been converted to subscription type, charge our clients thousands of dollars. and if you cancel your subscription, you can no longer use the software, not even adjust all entries. These days our clients pay thousands of dollars without even owning their licenses. There must be still some other software that allow you to have control over your license. This is insight contemplating to seek other solutions. Shame that in 2026, technologically we may be advanced, however ethically I have my concerns. I still value integrity and recommend to my clients not to fall in the trap of technology, but instead consider their needs.',
  'I find Sage accounting to be one of the most user friendly for all types of users. I consider it 95% complete. Which in my opinion excellent. No software solution in the market is genuine 100% complete. There will always be something missing.',
  'For Offline users it has become one of the worst. I do not recommend it 100% for offline users. It has become extremely expensive.',
  NULL,
  NULL,
  '2026-03-24',
  11,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Dylan W.',
  'Owner',
  'Dylan Retail Store',
  'Retail',
  '2-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  5,
  5,
  4,
  5,
  5,
  'Recommended Product',
  'A good all in one software to help organize and manage my business. The ease of invoicing and receiving payments is one of the best additional features.',
  'Sage has all the features I need to organize my business expenses and handle invoicing and inventory.',
  'The pricing is a bit on the expensive side for a small business. I don’t need all the functionality it provides.',
  NULL,
  NULL,
  '2026-04-27',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Évelyne F.',
  'Adjointe administrative',
  'NPO Hub',
  'Non-Profit Organization Management',
  '11-50',
  'South Africa',
  false,
  NULL,
  '2+ years',
  5,
  5,
  5,
  5,
  5,
  'Userfriendly, i recommand it !',
  'I use it every month for work and even recommand it to an other non-profit organisation to help them with their finances. It''s a time saver and really easy to use !',
  'Extremely clean interface, saves time, reports are generated instantly.',
  'No major issues, works beautifully for our NGO requirements.',
  NULL,
  NULL,
  '2026-04-21',
  6,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Jacki N.',
  'Bookkeeper',
  'HR Services South Africa',
  'Human Resources',
  '2-10',
  'South Africa',
  false,
  NULL,
  'Less than 6 months',
  5,
  5,
  4,
  4,
  4,
  'Happy With Moving to Sage Accounting',
  'I do like having a cloud based service and the onboarding was helpful. [sensitive content hidden] was great and helped answer a lot of questions even now, months later.',
  'I liked the intuitive nature of the program and auto integration of being able to issue invoices and collect payments automatically.',
  'I can''t upload our bank feed as it''s from a credit union. I''m not a huge fan of the bank rec process. I''d also like the ability to create custom reports.',
  NULL,
  NULL,
  '2026-04-22',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Ben F.',
  'Owner coach trainer',
  'Fitness and Sports Academy',
  'Sports',
  '2-10',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  4,
  4,
  4,
  4,
  4,
  'Accounting made easy',
  'Very positive in terms of time management and access to timely reports that allow for improve coordination',
  'Find a software easy to use access to videos for tutorials is made easy and just the simplification of having reporting',
  'Just the mundane business of receipts & data entry lol i’m hoping to find a scanning feature that helps this process',
  NULL,
  NULL,
  '2026-04-27',
  4,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Carol H.',
  'Owner',
  'Carol Boutique',
  'Retail',
  '2-10',
  'South Africa',
  false,
  NULL,
  'Less than 6 months',
  5,
  5,
  5,
  5,
  4,
  'Newbie loving it',
  'Im new learning books on my own and its pretty easy once you get started. I was terrified to start but im almost done 2025 and i feel better. So sage helped me i did try quick books nope not for me.',
  'The ease of the program I like using Sage because it keeps my bookkeeping simple, organized, and easy to manage. Instead of overcomplicating things, I can enter my transactions in a way that makes sense for how I actually run my business. I prefer working with monthly totals rather than hundreds of small entries, and Sage allows me to do that while still keeping everything accurate.',
  'Cant think of anything so far as i am still learning as of now im happy with it and the help links make it even better. Maybe add a chat to some thinks to help walk through would help more',
  NULL,
  NULL,
  '2026-04-21',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'LESLEY V.',
  'Accountant',
  'LV Bookkeeping',
  'Accounting',
  '11-50',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  5,
  5,
  5,
  5,
  5,
  'Sage Accounting is second to none - Don''t go anywhere else.',
  'Sage Accounting helps me get through the tasks of the day easily and quickly. The updates always change something for the better and any problems I have I know I can just ring up Sage and their knowledgable support staff can guide me through things or log in and sort it out extremely quickly.',
  'I''ve used Sage Accounting for 15 years and the software is second to none. The screens are easy to navigate, the reports are easily managed and amended to suit the client, it saves time with inputting when you can memorise a screen for future use. The customer support is exceptionally good. It enables me to log in and look at my clients accounts without having to visit their offices which in itself is time saving as I can spot any errors quickly and readjust where necesary or talk them through how to correct it.',
  'There is nothing I dislike about Sage Accounting. The design, the navigation and the ease of use has kept me using Sage Accounting for 15 years. I wouldn''t go anywhere else.',
  NULL,
  NULL,
  '2026-04-24',
  15,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Valerie M.',
  'Accountant',
  'Valerie Consulting Services',
  'Accounting',
  '11-50',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  4,
  3,
  3,
  4,
  4,
  'Sage50 versus Sage Cloud (not very innovative)',
  'I am a loyal and faithful person. I hope these fixes will be implemented quickly and that the product will be more competitive with QuickBooks and others.',
  'I have been using Sage 50 for over 15 years and I have always found this product very easy to use, fast in execution, with many reporting possibilities, very professional software and without bugs....But my enthusiasm flew away when I switched to Sage Cloud.',
  'For the past two years, I''ve migrated all my clients to Sage Cloud, thinking I was taking a step forward. But honestly, I regret my move. I feel like I''m going backward when it should be even faster and more efficient than Sage 50. And my clients aren''t very happy either. For example, one of my clients has five companies but manages everything under a single email address. However, it takes a different email address to open a new company, which I find ridiculous. Secondly, the project-based accounting isn''t very advanced. I can''t generate a single report with all the projects included. If I have 15 projects, I have to generate 15 separate reports. This will be nonsensical by 2026. The same goes for manually transferring GL balances to the net profit at the end of the year. This should be done automatically. These are just a few of the irritations I encounter on a daily basis.',
  NULL,
  NULL,
  '2026-01-20',
  18,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Allen S.',
  'Chief Financial Officer',
  'HR Capital Group',
  'Human Resources',
  '51-200',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '6-12 months',
  5,
  5,
  5,
  5,
  5,
  'The Easiest Accounting Experience I’ve Ever Had',
  'I can’t believe how much this has improved my day‑to‑day work! It’s incredibly easy to use and makes running my small business feel effortless. I actually enjoy using it—highly recommended!',
  'What stands out most is how straightforward the whole platform is. Bank reconciliation is effortless, and the reporting tools are ready to use right away, which saves a ton of time. The invoicing section is clean and easy, and the transaction‑matching feature does a great job preventing any double‑ups. It feels built with real‑world small business workflows in mind.',
  'My only real struggle has been handling irregular transactions such as bank‑reversed payments. The system works great overall, but these cases could be more intuitive.',
  NULL,
  NULL,
  '2026-01-20',
  10,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Jennae H.',
  'Administrator',
  'Cape Town Construction Ltd',
  'Construction',
  '11-50',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  5,
  5,
  5,
  1,
  4,
  'Great to use!',
  'I really enjoy it! It''s easier to use and the cost is great! I can easily report my finances and invoicing is a breeze.',
  'Its really easy to send invoices and you can see when the invoice was delevered and when it was seen. This way I know when my customers get my invoices.',
  'Trying to get a hold of customer service is a nightmare. I have had issues in the past and really needed to speak to someone and it was really hard to find any phone numbers or any contact info to help. I neded up figuring things out on my own but it took longer and was not easy to do.',
  NULL,
  NULL,
  '2025-09-19',
  13,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Shane C.',
  'Locksmith',
  'Shane Security & Automotive',
  'Automotive',
  '2-10',
  'South Africa',
  false,
  NULL,
  '6-12 months',
  4,
  4,
  5,
  3,
  3,
  'Mostly satisfied - could use a few more features',
  'For the most part Sage is an excellent product, but it could do with some improvements, things that would make me want to recommend this product to others, but Quickbooks has features that Sage doesn''t that made things run a bit smoother overall. However your price is very agreeable for our small business',
  'I like how easy it is to organize invoices, products and match banking records. The front page gives me a full view of of ingoing and outgoing expenses, I can see who still owes on invoices.',
  'I would love to see a rearrange lines in an estimate or a quote, I think that is a very big oversight, something I miss from using Quickbooks. The help pages don''t work on my browser (Chrome) which I think is pretty frustrating overall. I have noticed that the product filter doesn''t work very well, something else that I find frustrating when I am trying to work in sections of inventory.',
  NULL,
  NULL,
  '2025-12-18',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Aaron R.',
  'Certified Professional Bookkeeper',
  'Precision Bookkeeping',
  'Accounting',
  '2-10',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  2,
  3,
  2,
  3,
  2,
  'Give us the functionality we ask for!',
  'Honestly, wish you''d find a way to take Sage 50 and just make it cloud based. I love Sage 50. Sage Accounting is far too limited in functionality. It''s leagues behind Xero and QBO - I hate QBO personally.',
  'I like that my customers can do their own invoicing through Sage Accounting & I can pull the data in to Sage 50.',
  'The inability to give multiple users permissions to use the app. The inability to adjust tax codes for my own use. The inability to issue receipts - come on - why is this still an issue? Should have been included with the first release and we''ve been asking for this functionality forever. The inability to adjust invoices beyond the templates. Limited apps for integration.',
  NULL,
  NULL,
  '2025-11-04',
  22,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Chantal H.',
  'Accounting clerk',
  'Prime Consumer Services',
  'Consumer Services',
  '11-50',
  'South Africa',
  false,
  NULL,
  '6-12 months',
  4,
  4,
  4,
  4,
  4,
  'Easy and reliable',
  'So far I am happy with the overall experience and I will be more able to comment after at least one full year of using it.',
  'It is quite easy to use and has many functions that make the daily and monthly tasks easier. So far I enjoy working with Sage.',
  'The invoice models are very limited and also the layout and information that can be added. If proportional payments would be offered, it would also be something I would use.',
  NULL,
  NULL,
  '2025-12-02',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Sandi C.',
  'Owner',
  'Sandi Fine Furniture',
  'Furniture',
  '2-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  4,
  4,
  4,
  4,
  4,
  'Sage - Option',
  'Good but I haven''t had to use to much of the help options, except for payroll, so I am not sure how well that will work if needed.',
  'Simple to use and convenient if you need to make an adjustment. Compared to older versions of Sage this is easier to navigate.',
  'Payroll. I believe all the steps needed when to enter hourly employees bi-weekly hours is a little to many steps and double checks needed. You do get used to it, but it''s to many steps every time.',
  NULL,
  NULL,
  '2025-12-02',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Connie B.',
  'Owner',
  'Ongoing Living & Learning Inc.',
  'Civic & Social Organization',
  '2-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  5,
  5,
  5,
  4,
  4,
  'Ongoing Living & Learning Inc.',
  'Good. I also use Sage Intaact for my larger business. I find Sage perfect for the smaller side business - just enough accounting capabilities to not be confusing.',
  'Ease of use and learning tools. The invoicing tool works well for what I am using. We are a charity and appreciate the discounted fees very much.',
  'It keeps dropping my bank feed. I found the bank reconciliation a bit difficult with the dates. Do not like that if you approve a bank transaction in the banking feed past the end of the month when you do the reconciliation ending prior it will not allow it.',
  NULL,
  NULL,
  '2025-12-08',
  6,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Pierre-Marie D.',
  'President',
  'PMD Civil Engineering',
  'Civil Engineering',
  '11-50',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  2,
  3,
  2,
  1,
  2,
  'Pretty bad',
  'not very good, the product is very expensive for the fonctionality , i am keeping it just because migrating is a pain in the ...',
  'Relatively easy to use. not much else noce to say about it , I have to keep typing so i can press next.',
  'the customer service is really bad. the conectivity with the bank is always difficult. Some operations are tedious',
  NULL,
  NULL,
  '2026-03-12',
  19,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Michelle C.',
  'Owner',
  'Wellness & Fitness Studio',
  'Health, Wellness and Fitness',
  '2-10',
  'South Africa',
  false,
  NULL,
  '6-12 months',
  4,
  4,
  4,
  2,
  3,
  'Mediocre: Does the basics. Could be more efficient',
  'Ease of use but I''m wasting a lot of time uploading my bank transactions. I''ve tried reaching out on the chat multiple times and no one knows how to help me.',
  'I like the ease of use of Sage. It is very user friendly and provides reporting at a quick glance for me to see how my business is performing. Also makes my accounting easier.',
  'Slow. My bank transactions don''t upload automatically. I can connect my bank and then I have to manually load every transaction.',
  NULL,
  NULL,
  '2026-01-21',
  12,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Erika H.',
  'Business Owner',
  'Erika Retail Outlets',
  'Retail',
  '2-10',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  4,
  4,
  4,
  2,
  4,
  'To Sage or not to Sage online!',
  'Overall, switching to Sage online was an important part of the puzzle for me to transition into retirement.',
  'I appreciate that I can work from anywhere! I also love that my assistant and I can both work on Sage simultaneously and network from different locations.',
  'Customer service is the most difficult part of Sage. It is almost impossible to chat live with a human to figure out a problem.',
  NULL,
  NULL,
  '2025-12-12',
  11,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Liza T.',
  'Owner Operator',
  'LT Construction & Civils',
  'Construction',
  '2-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  4,
  4,
  4,
  4,
  4,
  'Reliable and straight forward',
  'Overall it is the best system I have used. I have been using Simply Accounting for over 20 year. I love that you can customize the system to suit your business needs.',
  'I have been using Simply Accounting for over 20 years. I love the simplicity of the system and how more in depth you can use it if you need to. Almost 2 years ago I changed from Sage 50 to the Sage one online system. It took some getting used to but I love I can work anywhere that has internet.',
  'I don''t like that you can''t search customers by address or ph #. On the Sage One I miss having the capabilities of memorized transactions',
  NULL,
  NULL,
  '2025-12-09',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Paul L.',
  'Co-owner',
  'Durban Food & Beverages',
  'Food & Beverages',
  '2-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  4,
  4,
  4,
  4,
  4,
  'Easy to use and very useful!',
  'Pleased with features and easy to use for invoicing. Helps us see where things are at, at any given time.',
  'One-stop shop for our business finances. Features and setup are practical. Easy to navigate and work with.',
  'Having only one person able to receive a code for logging in. Two of us use the account and when one gets logged out, the other has to get a code to log in. Only one person is able to get the code.',
  NULL,
  NULL,
  '2026-03-17',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Jayden L.',
  'VP of Accounting',
  'Jayden Projects Group',
  'Construction',
  '51-200',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  5,
  5,
  5,
  5,
  5,
  'SAGE 10/10 AMAZING CAN''T LIVE WITHOUT IT',
  '10/10 super easy to use and has a lot of great features to help me get what i need done. Whether it''s payables, receivables or reporting Sage is a platform that can do it all!',
  'Sage is an amazing product! Super easy to use both and easy to get customer support. We are a medium sized business, but this is perfect from all business ranging from small to conglomerates due to how easy it is to access and its value for money. The way that sage displays its data make it super easy for financial reporting. It is great for invoicing as well due to how well it displays data',
  'It is not a software you can learn within a day, however once you get the hang of it Sage is an irreplaceable tool!',
  NULL,
  NULL,
  '2026-03-13',
  14,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Mia D.',
  'Managing Director',
  'Mia D. Photography',
  'Photography',
  '2-10',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  4,
  4,
  4,
  3,
  4,
  'Sage cloud',
  'I was paying way too much for what I needed for years! Every year when renewing I would ask if there was a way to lower my subscription. The answer would be no. Last year however I insisted so much that I was prompted to a sage cloud, much cheaper and all that I needed. I resent that Sage kept this from me for years and made me pay a big bill for a system that I didn''t need.',
  'The new cloud system is intuitive and easy to use. I am much happier using the cloud, especially because it''s saving me money I didn''t need to spend to begin with.',
  'Poor customer service. I was not informed of less expensive possibilities that would have helped me save money.',
  NULL,
  NULL,
  '2026-05-23',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Nkosana M.',
  'Financial Manager',
  'Tech Solutions Holdings',
  'Hospitality',
  '51-200',
  'South Africa',
  true,
  NULL,
  '2+ years',
  5,
  4,
  5,
  5,
  5,
  'Fantastic VAT201 handling',
  'We have been using Sage for our accounting needs and it has made reporting and VAT compliance straightforward. The bank feeds save a lot of manual input.',
  'Audit trail compliance is robust and keeps our financial history highly transparent.',
  'Manual GL adjustments at year-end are required instead of being fully automated.',
  NULL,
  NULL,
  '2025-03-06',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Priya M.',
  'Practice Manager',
  'Tech Solutions Group',
  'Agriculture',
  '201-500',
  'South Africa',
  true,
  NULL,
  'Less than 6 months',
  5,
  5,
  5,
  5,
  4,
  'Reliable cloud accounting for SA SMBs',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-08-18',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Riaan M.',
  'Finance Clerk',
  'Engineering Partners',
  'Engineering',
  '51-200',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '2+ years',
  4,
  3,
  4,
  4,
  4,
  'Intuitive layout, simple to navigate',
  'We have been using Sage for our accounting needs and it has made reporting and VAT compliance straightforward. The bank feeds save a lot of manual input.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  NULL,
  NULL,
  '2026-02-16',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Aisha G.',
  'Practice Manager',
  'Retail Holdings',
  'Construction',
  '51-200',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  3,
  2,
  3,
  3,
  3,
  'Reliable cloud accounting for SA SMBs',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'User interface is clean and straightforward. Easy for non-accounting staff to invoice clients.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-11-14',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Boipelo V.',
  'Tax Practitioner',
  'Tech Solutions Holdings',
  'Logistics',
  '51-200',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  5,
  5,
  5,
  5,
  5,
  'Reliable cloud accounting for SA SMBs',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  NULL,
  NULL,
  '2026-02-07',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Melanie M.',
  'Managing Director',
  'Engineering Partners Holdings',
  'Wholesale',
  '51-200',
  'South Africa',
  true,
  NULL,
  '1-2 years',
  5,
  5,
  5,
  5,
  5,
  'Good features but some bugs exist',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'Great value for money compared to expensive offline ERP systems.',
  'Manual GL adjustments at year-end are required instead of being fully automated.',
  NULL,
  NULL,
  '2025-01-03',
  2,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Devon N.',
  'Partner',
  'Consulting Group Pty Ltd',
  'Non-Profit Organization Management',
  '51-200',
  'South Africa',
  true,
  NULL,
  '2+ years',
  4,
  4,
  4,
  4,
  5,
  'The industry standard for a reason',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2025-12-05',
  6,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Gareth G.',
  'Chartered Accountant',
  'Engineering Partners Pty Ltd',
  'Professional Services',
  '11-50',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  5,
  4,
  4,
  5,
  5,
  'Good features but some bugs exist',
  'We have been using Sage for our accounting needs and it has made reporting and VAT compliance straightforward. The bank feeds save a lot of manual input.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2026-02-28',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Melanie M.',
  'Practice Manager',
  'Property Group',
  'IT Services',
  '51-200',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '1-2 years',
  5,
  5,
  5,
  5,
  5,
  'Good value but pricing is creeping up',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-02-04',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Gareth V.',
  'Business Administrator',
  'Auto Repairs Pty Ltd',
  'Engineering',
  '11-50',
  'South Africa',
  true,
  NULL,
  'Less than 6 months',
  4,
  4,
  4,
  4,
  4,
  'Intuitive layout, simple to navigate',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2025-11-04',
  4,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Dineo M.',
  'Business Administrator',
  'Tech Solutions Holdings',
  'Construction',
  '1-10',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  4,
  3,
  4,
  4,
  5,
  'Reliable cloud accounting for SA SMBs',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Some batch editing functions freeze or load slowly when internet connection drops.',
  NULL,
  NULL,
  '2026-02-18',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Gideon M.',
  'Senior Bookkeeper',
  'Tech Solutions Pty Ltd',
  'Retail',
  '51-200',
  'South Africa',
  true,
  NULL,
  '2+ years',
  3,
  4,
  3,
  3,
  3,
  'Good value but pricing is creeping up',
  'We have been using Sage for our accounting needs and it has made reporting and VAT compliance straightforward. The bank feeds save a lot of manual input.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Pricing increases yearly, making it harder for very small businesses to justify.',
  NULL,
  NULL,
  '2025-10-21',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Boipelo M.',
  'Senior Bookkeeper',
  'Boutique Service Holdings',
  'IT Services',
  '1-10',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  5,
  5,
  5,
  5,
  5,
  'The industry standard for a reason',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'Simple and clean invoice templates that look highly professional.',
  'Occasional bank feed drops that require manual reconciliation or re-authentication.',
  NULL,
  NULL,
  '2025-10-28',
  1,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Hlengiwe F.',
  'Finance Clerk',
  'Distribution Ltd Holdings',
  'Wholesale',
  '11-50',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  3,
  3,
  4,
  2,
  2,
  'A solid upgrade from spreadsheets',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2026-03-01',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Johan Z.',
  'Managing Director',
  'Tourism & Travel',
  'Real Estate',
  '1-10',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '6-12 months',
  4,
  4,
  5,
  4,
  4,
  'Decent product but support can improve',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-08-17',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Tebogo N.',
  'Chartered Accountant',
  'Tech Solutions',
  'IT Services',
  '1-10',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  4,
  3,
  5,
  4,
  3,
  'Highly recommended for small practices',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Occasional bank feed drops that require manual reconciliation or re-authentication.',
  NULL,
  NULL,
  '2025-11-20',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Francois M.',
  'Chartered Accountant',
  'Engineering Partners Pty Ltd',
  'Wholesale',
  '1-10',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '6-12 months',
  3,
  2,
  3,
  2,
  3,
  'Highly recommended for small practices',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'Simple and clean invoice templates that look highly professional.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-07-29',
  6,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Dineo A.',
  'Owner',
  'Property Group Group',
  'Consulting',
  '201-500',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '6-12 months',
  5,
  5,
  5,
  5,
  5,
  'Decent product but support can improve',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'Lack of native payroll integration means we have to pay extra for third-party tools.',
  NULL,
  NULL,
  '2025-01-10',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Saray T.',
  'General Manager',
  'Logistics SA Holdings',
  'Professional Services',
  '51-200',
  'South Africa',
  true,
  NULL,
  'Less than 6 months',
  5,
  5,
  5,
  4,
  4,
  'The industry standard for a reason',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Some batch editing functions freeze or load slowly when internet connection drops.',
  NULL,
  NULL,
  '2025-12-15',
  2,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Ebrahim P.',
  'Managing Director',
  'Consulting Group',
  'Non-Profit Organization Management',
  '11-50',
  'South Africa',
  true,
  'Verified LinkedIn User',
  'Less than 6 months',
  3,
  3,
  3,
  2,
  3,
  'Fantastic VAT201 handling',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Great value for money compared to expensive offline ERP systems.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  NULL,
  NULL,
  '2026-04-07',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Riaan Z.',
  'Chartered Accountant',
  'Auto Repairs Group',
  'Real Estate',
  '51-200',
  'South Africa',
  false,
  NULL,
  '6-12 months',
  4,
  4,
  3,
  4,
  4,
  'Highly recommended for small practices',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2026-02-25',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Saray D.',
  'Operations Manager',
  'Property Group Holdings',
  'Education',
  '1-10',
  'South Africa',
  true,
  NULL,
  '2+ years',
  5,
  4,
  5,
  5,
  5,
  'Easy invoicing and bank feeds',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-06-01',
  4,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Dineo S.',
  'Practice Manager',
  'Engineering Partners',
  'Hospitality',
  '11-50',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  3,
  3,
  3,
  3,
  4,
  'Fantastic VAT201 handling',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Audit trail compliance is robust and keeps our financial history highly transparent.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-10-07',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Dineo B.',
  'Operations Manager',
  'Food Distributors Group',
  'Engineering',
  '201-500',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '2+ years',
  5,
  5,
  5,
  5,
  5,
  'The industry standard for a reason',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2026-03-14',
  1,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Kgomotso C.',
  'Managing Director',
  'Boutique Service',
  'Education',
  '201-500',
  'South Africa',
  false,
  NULL,
  '6-12 months',
  5,
  4,
  5,
  4,
  5,
  'Good value but pricing is creeping up',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'Some batch editing functions freeze or load slowly when internet connection drops.',
  NULL,
  NULL,
  '2025-03-20',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Hein L.',
  'Business Administrator',
  'Tourism & Travel Pty Ltd',
  'Non-Profit Organization Management',
  '1-10',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  2,
  2,
  2,
  2,
  1,
  'Decent product but support can improve',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Lack of native payroll integration means we have to pay extra for third-party tools.',
  NULL,
  NULL,
  '2026-05-08',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Nkosana P.',
  'Senior Bookkeeper',
  'Security Services Pty Ltd',
  'Manufacturing',
  '11-50',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  5,
  5,
  4,
  4,
  5,
  'Easy invoicing and bank feeds',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Lack of native payroll integration means we have to pay extra for third-party tools.',
  NULL,
  NULL,
  '2026-02-05',
  6,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Riaan D.',
  'Practice Manager',
  'Creative Studio Holdings',
  'Retail',
  '201-500',
  'South Africa',
  true,
  NULL,
  'Less than 6 months',
  4,
  4,
  4,
  4,
  3,
  'Decent product but support can improve',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'Audit trail compliance is robust and keeps our financial history highly transparent.',
  'Lack of native payroll integration means we have to pay extra for third-party tools.',
  NULL,
  NULL,
  '2025-04-26',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Andries G.',
  'Partner',
  'Tech Solutions Pty Ltd',
  'Agriculture',
  '1-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  4,
  5,
  3,
  4,
  4,
  'A solid upgrade from spreadsheets',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Occasional bank feed drops that require manual reconciliation or re-authentication.',
  NULL,
  NULL,
  '2025-03-22',
  1,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Nicole Z.',
  'General Manager',
  'Food Distributors Group',
  'Consulting',
  '51-200',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  5,
  5,
  5,
  4,
  5,
  'Easy invoicing and bank feeds',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-10-24',
  6,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Melanie M.',
  'Managing Director',
  'Distribution Ltd Pty Ltd',
  'Engineering',
  '51-200',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '1-2 years',
  4,
  4,
  3,
  3,
  3,
  'Decent product but support can improve',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'Great value for money compared to expensive offline ERP systems.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2026-01-06',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Charmaine M.',
  'Chartered Accountant',
  'Property Group',
  'Engineering',
  '51-200',
  'South Africa',
  true,
  NULL,
  '2+ years',
  3,
  4,
  3,
  3,
  3,
  'Easy invoicing and bank feeds',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'User interface is clean and straightforward. Easy for non-accounting staff to invoice clients.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2025-02-21',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Ebrahim B.',
  'Managing Director',
  'Boutique Service Group',
  'Engineering',
  '51-200',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '1-2 years',
  3,
  4,
  4,
  2,
  4,
  'The industry standard for a reason',
  'Good value for money. Very compliant with SARS requirements, though project accounting needs improvement.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-08-19',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Mthokozisi O.',
  'Operations Manager',
  'Creative Studio',
  'Real Estate',
  '11-50',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  4,
  5,
  5,
  3,
  5,
  'The industry standard for a reason',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2025-06-20',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Xolani K.',
  'Chartered Accountant',
  'Tech Solutions Pty Ltd',
  'Wholesale',
  '1-10',
  'South Africa',
  false,
  'Verified LinkedIn User',
  'Less than 6 months',
  5,
  5,
  5,
  5,
  5,
  'Reliable cloud accounting for SA SMBs',
  'Solid accounting software. The bank feeds and invoicing features are excellent, but payroll missing natively is a downside.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  NULL,
  NULL,
  '2025-10-21',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Kelebogile S.',
  'Partner',
  'Retail Holdings Holdings',
  'Professional Services',
  '1-10',
  'South Africa',
  false,
  NULL,
  '6-12 months',
  4,
  4,
  4,
  3,
  4,
  'A solid upgrade from spreadsheets',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'Being cloud-based allows me to check reports on the go from anywhere in South Africa.',
  'Manual GL adjustments at year-end are required instead of being fully automated.',
  NULL,
  NULL,
  '2025-07-05',
  1,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Ebrahim B.',
  'CFO',
  'Trading Enterprise Holdings',
  'Education',
  '11-50',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  5,
  4,
  5,
  5,
  5,
  'The industry standard for a reason',
  'Good value for money. Very compliant with SARS requirements, though project accounting needs improvement.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-08-07',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Pieter J.',
  'Owner',
  'Engineering Partners',
  'IT Services',
  '11-50',
  'South Africa',
  true,
  NULL,
  'Less than 6 months',
  4,
  3,
  5,
  4,
  5,
  'Intuitive layout, simple to navigate',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Great value for money compared to expensive offline ERP systems.',
  'Pricing increases yearly, making it harder for very small businesses to justify.',
  NULL,
  NULL,
  '2025-11-05',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Zanele Z.',
  'Chartered Accountant',
  'Retail Holdings Pty Ltd',
  'Agriculture',
  '11-50',
  'South Africa',
  true,
  NULL,
  'Less than 6 months',
  5,
  5,
  5,
  5,
  5,
  'The industry standard for a reason',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'Some batch editing functions freeze or load slowly when internet connection drops.',
  NULL,
  NULL,
  '2025-09-27',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Mbali G.',
  'Managing Director',
  'Retail Holdings Pty Ltd',
  'Real Estate',
  '11-50',
  'South Africa',
  false,
  'Verified LinkedIn User',
  'Less than 6 months',
  5,
  5,
  5,
  5,
  5,
  'Fantastic VAT201 handling',
  'We have been using Sage for our accounting needs and it has made reporting and VAT compliance straightforward. The bank feeds save a lot of manual input.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-07-11',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Charmaine L.',
  'Senior Bookkeeper',
  'Security Services Holdings',
  'Manufacturing',
  '201-500',
  'South Africa',
  false,
  NULL,
  '6-12 months',
  5,
  5,
  5,
  5,
  5,
  'Good value but pricing is creeping up',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-05-22',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Gary K.',
  'Finance Director',
  'Security Services',
  'Education',
  '201-500',
  'South Africa',
  false,
  NULL,
  '6-12 months',
  5,
  5,
  4,
  5,
  5,
  'The industry standard for a reason',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Occasional bank feed drops that require manual reconciliation or re-authentication.',
  NULL,
  NULL,
  '2026-02-28',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Precious B.',
  'Managing Director',
  'Tech Solutions Holdings',
  'Real Estate',
  '11-50',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '2+ years',
  5,
  5,
  5,
  5,
  4,
  'Highly recommended for small practices',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2026-04-11',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Ruan N.',
  'Senior Bookkeeper',
  'Trading Enterprise Pty Ltd',
  'Agriculture',
  '51-200',
  'South Africa',
  true,
  NULL,
  '1-2 years',
  5,
  4,
  5,
  5,
  5,
  'Intuitive layout, simple to navigate',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2025-07-02',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Dineo M.',
  'Operations Manager',
  'Security Services',
  'Agriculture',
  '201-500',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  4,
  5,
  5,
  4,
  4,
  'Intuitive layout, simple to navigate',
  'Good value for money. Very compliant with SARS requirements, though project accounting needs improvement.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  NULL,
  NULL,
  '2025-03-04',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Nkosana V.',
  'Finance Director',
  'Security Services Group',
  'Wholesale',
  '51-200',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  5,
  5,
  5,
  4,
  4,
  'The industry standard for a reason',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2026-02-07',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Kobus G.',
  'Operations Manager',
  'Tourism & Travel Pty Ltd',
  'Healthcare',
  '1-10',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  3,
  2,
  3,
  3,
  4,
  'Intuitive layout, simple to navigate',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'Being cloud-based allows me to check reports on the go from anywhere in South Africa.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  NULL,
  NULL,
  '2025-07-03',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Hein B.',
  'Owner',
  'Engineering Partners Pty Ltd',
  'Hospitality',
  '11-50',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '1-2 years',
  2,
  3,
  3,
  2,
  2,
  'Intuitive layout, simple to navigate',
  'Good value for money. Very compliant with SARS requirements, though project accounting needs improvement.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Lack of native payroll integration means we have to pay extra for third-party tools.',
  NULL,
  NULL,
  '2025-08-31',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Nkosana P.',
  'Finance Clerk',
  'Food Distributors',
  'Wholesale',
  '201-500',
  'South Africa',
  true,
  'Verified LinkedIn User',
  'Less than 6 months',
  5,
  5,
  5,
  4,
  5,
  'A solid upgrade from spreadsheets',
  'Overall, it is a great tool for small business bookkeeping. Customer support is helpful but the waiting queue during tax seasons is long.',
  'Audit trail compliance is robust and keeps our financial history highly transparent.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2025-07-23',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Zuki B.',
  'Finance Director',
  'Auto Repairs Holdings',
  'Manufacturing',
  '201-500',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  5,
  5,
  4,
  5,
  4,
  'Intuitive layout, simple to navigate',
  'Solid accounting software. The bank feeds and invoicing features are excellent, but payroll missing natively is a downside.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Manual GL adjustments at year-end are required instead of being fully automated.',
  NULL,
  NULL,
  '2025-10-05',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Lungile S.',
  'Senior Bookkeeper',
  'Retail Holdings Group',
  'Healthcare',
  '201-500',
  'South Africa',
  true,
  NULL,
  '2+ years',
  5,
  5,
  5,
  4,
  4,
  'Good value but pricing is creeping up',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'Being cloud-based allows me to check reports on the go from anywhere in South Africa.',
  'Manual GL adjustments at year-end are required instead of being fully automated.',
  NULL,
  NULL,
  '2025-08-12',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Dineo P.',
  'Finance Clerk',
  'Construction Services Holdings',
  'Engineering',
  '51-200',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '6-12 months',
  4,
  3,
  3,
  4,
  5,
  'Intuitive layout, simple to navigate',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2025-06-15',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Hlengiwe Z.',
  'Managing Director',
  'Boutique Service Group',
  'Non-Profit Organization Management',
  '11-50',
  'South Africa',
  true,
  'Verified LinkedIn User',
  'Less than 6 months',
  3,
  3,
  4,
  3,
  2,
  'Decent product but support can improve',
  'Solid accounting software. The bank feeds and invoicing features are excellent, but payroll missing natively is a downside.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-02-18',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Gideon M.',
  'Managing Director',
  'Logistics SA Holdings',
  'Manufacturing',
  '201-500',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  5,
  5,
  5,
  4,
  5,
  'Highly recommended for small practices',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2025-07-23',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Sipho T.',
  'Chartered Accountant',
  'Tourism & Travel Holdings',
  'Professional Services',
  '51-200',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  5,
  5,
  5,
  5,
  5,
  'Good value but pricing is creeping up',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Being cloud-based allows me to check reports on the go from anywhere in South Africa.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2026-03-03',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Charmaine M.',
  'Partner',
  'Auto Repairs Group',
  'Professional Services',
  '11-50',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  4,
  4,
  3,
  4,
  4,
  'Highly recommended for small practices',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'Great value for money compared to expensive offline ERP systems.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2025-03-01',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Rene K.',
  'Business Administrator',
  'Property Group Group',
  'IT Services',
  '201-500',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '1-2 years',
  3,
  4,
  4,
  2,
  3,
  'Good features but some bugs exist',
  'Good value for money. Very compliant with SARS requirements, though project accounting needs improvement.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-06-17',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Mark T.',
  'Financial Manager',
  'Auto Repairs Holdings',
  'Retail',
  '51-200',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  5,
  5,
  5,
  5,
  5,
  'Good value but pricing is creeping up',
  'Solid accounting software. The bank feeds and invoicing features are excellent, but payroll missing natively is a downside.',
  'Simple and clean invoice templates that look highly professional.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-01-06',
  2,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Wayne M.',
  'Owner',
  'Food Distributors',
  'Professional Services',
  '201-500',
  'South Africa',
  true,
  NULL,
  'Less than 6 months',
  4,
  4,
  4,
  4,
  5,
  'Good value but pricing is creeping up',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2026-04-27',
  1,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Gary N.',
  'Partner',
  'Engineering Partners',
  'Healthcare',
  '1-10',
  'South Africa',
  true,
  'Verified LinkedIn User',
  'Less than 6 months',
  4,
  5,
  4,
  3,
  3,
  'A solid upgrade from spreadsheets',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-06-20',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Wayne T.',
  'Partner',
  'Security Services Pty Ltd',
  'Logistics',
  '1-10',
  'South Africa',
  true,
  NULL,
  '2+ years',
  5,
  5,
  5,
  4,
  5,
  'The industry standard for a reason',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Great value for money compared to expensive offline ERP systems.',
  'Some batch editing functions freeze or load slowly when internet connection drops.',
  NULL,
  NULL,
  '2026-05-10',
  2,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Lungile S.',
  'Managing Director',
  'Creative Studio Holdings',
  'Professional Services',
  '11-50',
  'South Africa',
  false,
  NULL,
  '2+ years',
  4,
  3,
  4,
  4,
  4,
  'Intuitive layout, simple to navigate',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Manual GL adjustments at year-end are required instead of being fully automated.',
  NULL,
  NULL,
  '2026-05-07',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Tebogo M.',
  'Senior Bookkeeper',
  'Tech Solutions Holdings',
  'Real Estate',
  '201-500',
  'South Africa',
  true,
  'Verified LinkedIn User',
  'Less than 6 months',
  5,
  5,
  5,
  4,
  5,
  'Decent product but support can improve',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Pricing increases yearly, making it harder for very small businesses to justify.',
  NULL,
  NULL,
  '2026-05-29',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Devon v.',
  'Business Administrator',
  'Property Group Holdings',
  'Hospitality',
  '201-500',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '1-2 years',
  3,
  3,
  3,
  3,
  2,
  'Good features but some bugs exist',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'Simple and clean invoice templates that look highly professional.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2025-02-19',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Nkosana N.',
  'Senior Bookkeeper',
  'Security Services',
  'Education',
  '11-50',
  'South Africa',
  true,
  NULL,
  '2+ years',
  3,
  4,
  2,
  3,
  2,
  'Highly recommended for small practices',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Some batch editing functions freeze or load slowly when internet connection drops.',
  NULL,
  NULL,
  '2026-01-26',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Lindiwe L.',
  'CFO',
  'Property Group',
  'Consulting',
  '1-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  5,
  5,
  5,
  5,
  5,
  'Fantastic VAT201 handling',
  'Good software with a clean user interface. It has helped us organize our business finances and invoicing, though there are minor bugs.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'Some batch editing functions freeze or load slowly when internet connection drops.',
  NULL,
  NULL,
  '2025-12-01',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Johan G.',
  'CFO',
  'Boutique Service Holdings',
  'Construction',
  '201-500',
  'South Africa',
  false,
  'Verified LinkedIn User',
  'Less than 6 months',
  4,
  5,
  5,
  4,
  3,
  'Easy invoicing and bank feeds',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'User interface is clean and straightforward. Easy for non-accounting staff to invoice clients.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2025-04-19',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Tshepo Z.',
  'Tax Practitioner',
  'Consulting Group Holdings',
  'Non-Profit Organization Management',
  '1-10',
  'South Africa',
  false,
  NULL,
  'Less than 6 months',
  3,
  3,
  4,
  3,
  2,
  'Decent product but support can improve',
  'Good value for money. Very compliant with SARS requirements, though project accounting needs improvement.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-02-06',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Chantel M.',
  'Finance Director',
  'Tourism & Travel Pty Ltd',
  'Manufacturing',
  '1-10',
  'South Africa',
  false,
  NULL,
  '2+ years',
  4,
  3,
  4,
  4,
  4,
  'Good value but pricing is creeping up',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'The customer support team is knowledgeable and assists quickly once you get through.',
  'Pricing increases yearly, making it harder for very small businesses to justify.',
  NULL,
  NULL,
  '2025-06-02',
  2,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Bongani M.',
  'Owner',
  'Engineering Partners Holdings',
  'Retail',
  '51-200',
  'South Africa',
  true,
  NULL,
  '1-2 years',
  3,
  3,
  4,
  2,
  4,
  'Decent product but support can improve',
  'A reliable product that does exactly what it says. Bank reconciliation is simple and the invoice creation is quick.',
  'Very reliable VAT201 generation which saves our team hours when filing returns.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  NULL,
  NULL,
  '2026-04-17',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Saray V.',
  'General Manager',
  'Distribution Ltd Group',
  'Education',
  '1-10',
  'South Africa',
  false,
  'Verified LinkedIn User',
  'Less than 6 months',
  5,
  5,
  4,
  5,
  5,
  'The industry standard for a reason',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'Great value for money compared to expensive offline ERP systems.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2025-01-28',
  6,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Tebogo P.',
  'Finance Clerk',
  'Consulting Group Pty Ltd',
  'Real Estate',
  '51-200',
  'South Africa',
  false,
  'Verified LinkedIn User',
  'Less than 6 months',
  3,
  3,
  2,
  3,
  4,
  'The industry standard for a reason',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'Being cloud-based allows me to check reports on the go from anywhere in South Africa.',
  'Pricing increases yearly, making it harder for very small businesses to justify.',
  NULL,
  NULL,
  '2025-05-23',
  8,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Anneri v.',
  'Managing Director',
  'Logistics SA Group',
  'IT Services',
  '1-10',
  'South Africa',
  false,
  NULL,
  '1-2 years',
  4,
  4,
  4,
  4,
  3,
  'Fantastic VAT201 handling',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'Audit trail compliance is robust and keeps our financial history highly transparent.',
  'Lack of native payroll integration means we have to pay extra for third-party tools.',
  NULL,
  NULL,
  '2025-02-09',
  1,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Hlengiwe N.',
  'CFO',
  'Retail Holdings Pty Ltd',
  'Non-Profit Organization Management',
  '11-50',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '6-12 months',
  5,
  4,
  4,
  5,
  4,
  'Easy invoicing and bank feeds',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'Audit trail compliance is robust and keeps our financial history highly transparent.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-11-20',
  4,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Ruan v.',
  'Practice Manager',
  'Consulting Group Pty Ltd',
  'Non-Profit Organization Management',
  '51-200',
  'South Africa',
  false,
  'Verified LinkedIn User',
  'Less than 6 months',
  4,
  5,
  4,
  4,
  4,
  'Intuitive layout, simple to navigate',
  'Good value for money. Very compliant with SARS requirements, though project accounting needs improvement.',
  'Simple and clean invoice templates that look highly professional.',
  'Initial chart of accounts setup was complex and took some hours to customize.',
  NULL,
  NULL,
  '2025-02-24',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Dineo M.',
  'Senior Bookkeeper',
  'Logistics SA Holdings',
  'Real Estate',
  '51-200',
  'South Africa',
  true,
  NULL,
  '6-12 months',
  5,
  5,
  4,
  5,
  5,
  'Good features but some bugs exist',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'User interface is clean and straightforward. Easy for non-accounting staff to invoice clients.',
  'Manual GL adjustments at year-end are required instead of being fully automated.',
  NULL,
  NULL,
  '2026-01-24',
  0,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Charmaine D.',
  'Owner',
  'Retail Holdings Pty Ltd',
  'Real Estate',
  '201-500',
  'South Africa',
  true,
  'Verified LinkedIn User',
  'Less than 6 months',
  3,
  2,
  2,
  2,
  3,
  'Reliable cloud accounting for SA SMBs',
  'We migrated from Excel and the difference in efficiency is huge. The automated matching helps prevent double-entries.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Customer support hold times can be quite long during SARS tax filing seasons.',
  NULL,
  NULL,
  '2025-06-07',
  7,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Kelebogile M.',
  'Financial Manager',
  'Construction Services Group',
  'IT Services',
  '1-10',
  'South Africa',
  true,
  'Verified LinkedIn User',
  '2+ years',
  4,
  4,
  5,
  4,
  4,
  'Good value but pricing is creeping up',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'The mobile app is very basic and does not support full reporting capabilities.',
  NULL,
  NULL,
  '2025-06-04',
  9,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Jacques D.',
  'Chartered Accountant',
  'Trading Enterprise Holdings',
  'Hospitality',
  '1-10',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '1-2 years',
  3,
  2,
  3,
  3,
  2,
  'Decent product but support can improve',
  'Great for tracking expenses and invoicing customers. The audit log is very helpful for our year-end reviews.',
  'Great value for money compared to expensive offline ERP systems.',
  'Occasional bank feed drops that require manual reconciliation or re-authentication.',
  NULL,
  NULL,
  '2026-05-26',
  3,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Sipho V.',
  'Practice Manager',
  'Auto Repairs Group',
  'Healthcare',
  '1-10',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  3,
  2,
  2,
  2,
  4,
  'Reliable cloud accounting for SA SMBs',
  'A user-friendly system that simplifies tax compliance. Highly recommended for South African business owners.',
  'User interface is clean and straightforward. Easy for non-accounting staff to invoice clients.',
  'Report customization options are slightly limited compared to QuickBooks Online.',
  NULL,
  NULL,
  '2026-03-02',
  4,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Priya v.',
  'General Manager',
  'Distribution Ltd Group',
  'Manufacturing',
  '51-200',
  'South Africa',
  true,
  NULL,
  '2+ years',
  3,
  2,
  2,
  2,
  4,
  'Reliable cloud accounting for SA SMBs',
  'Solid accounting software. The bank feeds and invoicing features are excellent, but payroll missing natively is a downside.',
  'Multi-user access with customizable permissions works great for our growing office.',
  'Project-based tracking is tedious to set up and report on separately.',
  NULL,
  NULL,
  '2025-06-05',
  5,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Lindiwe S.',
  'Senior Bookkeeper',
  'Engineering Partners Pty Ltd',
  'Real Estate',
  '1-10',
  'South Africa',
  true,
  NULL,
  '2+ years',
  4,
  5,
  4,
  4,
  4,
  'The industry standard for a reason',
  'Solid accounting software. The bank feeds and invoicing features are excellent, but payroll missing natively is a downside.',
  'Bank feeds from FNB and Standard Bank sync automatically, making daily reconciliation extremely fast.',
  'Lack of native payroll integration means we have to pay extra for third-party tools.',
  NULL,
  NULL,
  '2026-02-09',
  4,
  'published'
),
(
  (SELECT id FROM software WHERE slug = 'sage-accounting'),
  'Mark Z.',
  'Managing Director',
  'Construction Services Pty Ltd',
  'Engineering',
  '201-500',
  'South Africa',
  false,
  'Verified LinkedIn User',
  '6-12 months',
  4,
  3,
  4,
  4,
  5,
  'Fantastic VAT201 handling',
  'It works well for our daily administrative tasks. Financial reports are adequate and get the job done quickly.',
  'Decent inventory tracking for small volumes that integrates directly with our invoicing.',
  'Some batch editing functions freeze or load slowly when internet connection drops.',
  NULL,
  NULL,
  '2025-07-28',
  7,
  'published'
);

COMMIT;
