-- ============================================================================
-- SQL Seed File for Xero Reviews (44 Total Reviews)
-- Dynamically targets the software ID using a subquery based on the slug 'xero'.
-- Deletes any existing reviews for this software to prevent duplicates/placeholders.
-- ============================================================================

BEGIN;

-- Resolve the software ID and clean up any current reviews for Xero
DELETE FROM reviews WHERE software_id = (SELECT id FROM software WHERE slug = 'xero');

-- Insert reviews
INSERT INTO reviews (
  software_id,
  reviewer_name,
  reviewer_job_title,
  reviewer_company,
  reviewer_industry,
  reviewer_company_size,
  reviewer_country,
  verified_linkedin,
  verified_badge,
  used_for_duration,
  overall_rating,
  ease_of_use,
  value_for_money,
  customer_service,
  functionality,
  review_title,
  summary,
  pros,
  cons,
  vendor_response,
  vendor_response_date,
  review_date,
  helpful_count,
  status
) VALUES
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Rebecca R$q$,
  $q$Production manager$q$,
  NULL,
  $q$Construction$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$1-2 years$q$,
  5,
  5,
  5,
  NULL,
  5,
  $q$Seamless bank integrations and cloud-based access$q$,
  $q$I also appreciate the cloud-based access, which allows me to manage accounting from anywhere, along with the seamless bank integrations that help save time and keep records accurate.$q$,
  $q$I appreciate the cloud-based access, which allows me to manage accounting from anywhere, along with the seamless bank integrations that help save time and keep records accurate.$q$,
  NULL,
  NULL,
  NULL,
  $q$2026-05-22$q$,
  0,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Danielle T$q$,
  $q$AP, AR, Payroll$q$,
  NULL,
  $q$Mechanical or Industrial Engineering$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$More than 2 years$q$,
  2,
  2,
  3,
  NULL,
  2,
  $q$Multi-entity access issues and crashes$q$,
  $q$When you have more than one entity i find that you cant look at two company files at the same time one kick s the other one out and then it crashed TAHT is sooooo annoying as i have to have atleast 2 entitoies open everye day$q$,
  NULL,
  $q$When you have more than one entity i find that you cant look at two company files at the same time one kick s the other one out and then it crashed TAHT is sooooo annoying as i have to have atleast 2 entitoies open everye day$q$,
  NULL,
  NULL,
  $q$2026-03-04$q$,
  0,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Nikki C$q$,
  $q$permit technician$q$,
  NULL,
  $q$Construction$q$,
  $q$2-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$More than 2 years$q$,
  5,
  5,
  5,
  NULL,
  5,
  $q$Clean, easy-to-use interface and automation features$q$,
  $q$What I like most about Xero is its clean, easy-to-use interface and automation features, especially bank reconciliation and invoicing, which save time and make managing finances much more straightforward.$q$,
  $q$What I like most about Xero is its clean, easy-to-use interface and automation features, especially bank reconciliation and invoicing, which save time and make managing finances much more straightforward.$q$,
  NULL,
  NULL,
  NULL,
  $q$2026-04-27$q$,
  0,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Bill N$q$,
  $q$Senior Financial Accountant$q$,
  NULL,
  $q$Accounting$q$,
  $q$501-1,000$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$1-2 years$q$,
  3,
  3,
  3,
  NULL,
  3,
  $q$Workflows and reporting lack flexibility for growing ERP needs$q$,
  $q$Reporting and workflows aren’t very flexible like some other larger ERP systems, which can be frustrating especially as our company grew in size and required more advanced and granular reporting.$q$,
  NULL,
  $q$Reporting and workflows aren’t very flexible like some other larger ERP systems, which can be frustrating especially as our company grew in size and required more advanced and granular reporting.$q$,
  NULL,
  NULL,
  $q$2026-04-19$q$,
  0,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Debbie M.$q$,
  $q$Owner$q$,
  NULL,
  $q$Accounting$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  5,
  5,
  3,
  2,
  4,
  $q$Xero is ok$q$,
  $q$I’m generally happy with Xero. It’s very easy to use and integrates well with other products, though often at an additional cost. Its reporting features are somewhat limited, but they’re sufficient for what I need.$q$,
  $q$The dashboard is easy to use, the reporting functions work well, and I’m not aware of any bugs or issues. Recording transactions is straightforward, and keeping bank activity up to date is simple.$q$,
  $q$It does not offer good value for money compared with competitor products, and customer support is not available by telephone. As a partner, commission opportunities are limited, and payments are taken by direct debit.$q$,
  NULL,
  NULL,
  $q$2026-01-03$q$,
  15,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Cecilia G.$q$,
  $q$Administration$q$,
  NULL,
  $q$Religious Institutions$q$,
  $q$2-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$6-12 months$q$,
  4,
  4,
  3,
  NULL,
  4,
  $q$User-Friendly Interface$q$,
  $q$simplifies daily bookkeeping with intuitive features, real-time bank feeds, and seamless third-party integrations.$q$,
  $q$The dashboard is clean, modern, and easy to navigate even if you have no formal accounting background.$q$,
  $q$Xero’s subscription tiers have increased in cost, which can become expensive for users. The built-in reporting can feel slightly basic if you need advanced customization.$q$,
  NULL,
  NULL,
  $q$2026-05-26$q$,
  2,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Chloe S.$q$,
  $q$Bookkeeper$q$,
  NULL,
  $q$Accounting$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$Less than 6 months$q$,
  1,
  3,
  1,
  NULL,
  2,
  $q$Beware of the system$q$,
  $q$My overall experience with Xero is that it used to be one of the cheaper options for small businesses and it can be good for accounts with very little traffic. However other subscriptions are better for the price point.$q$,
  $q$Xero is good for bank account reconciliation when it syncs with your account. It is good for testing as it has a demo company you can always reach$q$,
  $q$Xero compared to other softwares add five extra steps when there only needs to be one. The tax set up is horrible and pulls up many errors. Everything goes to a suspense account that needs manual clearing and integrations are blocked so you have to approve them in Xero as well$q$,
  NULL,
  NULL,
  $q$2026-06-03$q$,
  5,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Thomas O.$q$,
  $q$Group Financial Controller$q$,
  NULL,
  $q$Accounting$q$,
  $q$51-200$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  4,
  4,
  4,
  NULL,
  4,
  $q$A time saver which has formalised out processes, but minor concerns over functionality and fees$q$,
  $q$We have leveraged Xero to speed up and formalise the controls around finances and accounts preparation. For smaller entities with few transactions it can be a challenge to justify the fees, but having cloud based software is very handy where we have multiple infrequent users vs manging installed software.$q$,
  $q$With Xero we can automate recurring quarterly billing, speeding up the process vs manual invoicing. For audited entities it is very easy to give read only access to Xero to the audit team, which is a significant time saver. It is very easy to link Barclays bank accounts - transactions feed into Xero regularly making it easy to reconcile transactions without the manual process of logging into the bank portal.$q$,
  $q$No in house consolidation between companies. Slight concerns over pricing prices / frequent price increases, for most entities Xero is reasonable value for money, but we have an entity we are not migrating to Xero as it has a USD bank account which would require a premium (more expensive) Xero package. Xero's budgeting / forecasting functions doesn't work correctly for us (changes not saved and budgets not populating correctly) and so we still maintain budgets on spreadsheets.$q$,
  NULL,
  NULL,
  $q$2026-03-01$q$,
  8,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Meredith R.$q$,
  $q$Owner$q$,
  NULL,
  $q$Health, Wellness and Fitness$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$6-12 months$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Great experience using Xero for small business accounting$q$,
  $q$Very positive, and I’m very glad we made the switch. The switch from another program took some effort but it’s been pretty straightforward ever since.$q$,
  $q$Extremely affordable cost and the functionality is right up there with other name-brand programs. My accountant loves it and funds it very intuitive.$q$,
  $q$Honestly, not much. There were a few minor challenges with account setup but xero’s support team was very responsive$q$,
  NULL,
  NULL,
  $q$2026-05-01$q$,
  3,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Verified Reviewer$q$,
  $q$Treasury Accountant$q$,
  NULL,
  $q$Food & Beverages$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$Less than 6 months$q$,
  4,
  4,
  4,
  NULL,
  4,
  $q$Efficient and User-Friendly Accounting, with Minor Limitations for Advanced Needs$q$,
  $q$My overall experience with Xero has been very positive, especially for managing day-to-day accounting tasks efficiently. The platform is easy to navigate, and features like bank reconciliation, invoicing, and real-time financial tracking make routine processes much quicker and more organized. It’s particularly useful for keeping everything in one place without needing multiple tools. At the same time, I’ve found that for more complex requirements, like detailed reporting or advanced customizations, it can feel a bit limited and sometimes requires workarounds using external tools. Despite that, for regular accounting needs and overall usability, it’s a reliable and user-friendly solution that has significantly improved workflow efficiency.$q$,
  $q$What I like most about Xero is how intuitive and time-saving it is for day-to-day financial management. The dashboard gives a clear, real-time view of cash flow, bank balances, and outstanding invoices, which makes decision-making much easier. I’ve found the bank reconciliation feature especially efficient, it automatically matches transactions and significantly reduces manual effort. The invoicing function is also smooth, with easy customization and quick sharing options, which helps streamline client interactions. That said, while it’s great for standard accounting needs, it can feel slightly limited when dealing with more complex reporting or highly customized requirements. Overall, it strikes a good balance between usability and functionality, especially for small to mid-sized businesses looking for a reliable, cloud-based accounting solution.$q$,
  $q$What I like least about Xero is that some of its advanced features can feel limited, particularly when it comes to highly customized reporting or complex financial analysis. For example, generating detailed, tailored reports often requires exporting data to Excel, which adds an extra step. I’ve also noticed that as transaction volume increases, the platform can occasionally feel slower, especially during bank reconciliation or when loading reports. Additionally, certain features like multi-currency handling or more advanced integrations, are only available in higher-tier plans, which can make it less cost-effective for growing businesses.$q$,
  NULL,
  NULL,
  $q$2026-04-12$q$,
  12,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Jasmine C.$q$,
  $q$Accountant$q$,
  NULL,
  $q$Accounting$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  5,
  NULL,
  5,
  $q$Perfect for small businesses$q$,
  $q$Xero is one of the best accounting softwares I have used. It's very user friendly and perfect for small businesses. The limitation is for bigger businesses that have multiple subsidiaries, however for small businesses wanting to manage everyday accounting, it's the perfect choice.$q$,
  $q$It's very user friendly. The bank feeds, journals, AP and AR function are all very straightforward and the layout is nice to use.$q$,
  $q$Importing the chart of accounts can get a bit complicated, but that's expected. There's not much else I don't like.$q$,
  NULL,
  NULL,
  $q$2026-04-22$q$,
  4,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Navpreet K.$q$,
  $q$Manager and CPA$q$,
  NULL,
  $q$Accounting$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$1-2 years$q$,
  5,
  5,
  5,
  4,
  5,
  $q$Simple and easy to use$q$,
  $q$My overall experience is that the cloud-based system allows users to access their financial information from anywhere, and its integration with many third-party apps makes workflow management much more efficient for reporting and any other tasks. It can be accessible through mobile.$q$,
  $q$Xero is an excellent accounting platform for small and medium-sized businesses. I really like its clean and easy-to-use interface, which makes invoicing, expense tracking, payroll, and bank reconciliation simple to manage.$q$,
  $q$One thing I like less about Xero is that some advanced accounting features can take time to learn for new users. In addition, customer support response times may occasionally be slower during busy periods, and certain features may require higher-priced plans.$q$,
  NULL,
  NULL,
  $q$2026-05-20$q$,
  6,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Rachel T.$q$,
  $q$Accounts Administrator$q$,
  NULL,
  $q$Construction$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  4,
  4,
  4,
  NULL,
  4,
  $q$Xero Review$q$,
  $q$Overall, I find Xero very easy to use and it produces the reports we need well. Xero keeps us well informed with changes.$q$,
  $q$Bank reconciliations are quick and easy with the "match" function which easily allocates receipts. Being able to memorise bills also saves time entering.$q$,
  $q$Lately there have been some software issues which slowed things down, but these happen rarely. Overall performance is great.$q$,
  NULL,
  NULL,
  $q$2026-05-17$q$,
  2,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Alissa P.$q$,
  $q$AGENT$q$,
  NULL,
  $q$Transportation/Trucking/Railroad$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$Less than 6 months$q$,
  5,
  5,
  5,
  3,
  5,
  $q$Simple and Reliable Accounting Made Easy$q$,
  $q$It’s a reliable and user-friendly accounting platform that makes day-to-day financial management easy and efficient. It’s a great option for businesses looking for a simple but powerful solution.$q$,
  $q$Very easy to use and makes managing finances simple. The invoicing and reporting features are strong, and the dashboard gives a clear overview of everything in one place$q$,
  $q$There are occasional minor bugs, but nothing that significantly impacts use. Customer service slow at times.$q$,
  NULL,
  NULL,
  $q$2026-04-12$q$,
  1,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Lisa R.$q$,
  $q$Office manager$q$,
  NULL,
  $q$Utilities$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$1-2 years$q$,
  5,
  5,
  5,
  NULL,
  5,
  $q$Xero for Invoicing and reporting$q$,
  $q$Overall I like the flexibility of the invoicing and reporting within Xero. We do not use the online payment option, yet. I would highly recommend.$q$,
  $q$The process for entering invoices and tracking what we are billing is very easy. I can easily pull reporting (balance reports, invoices, profit and loss, etc). This software is a great value for the money. I have not experienced any bugs or issues.$q$,
  $q$The reason I originally did not use Xero was because our bank does not connect with Xero. Our accountant manually adds the data from the bank. This is on my bank though, not Xero.$q$,
  NULL,
  NULL,
  $q$2025-10-16$q$,
  4,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Matthew C.$q$,
  $q$Director$q$,
  NULL,
  $q$Machinery$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  5,
  5,
  5,
  NULL,
  5,
  $q$Xero - a great fit for our small business$q$,
  $q$In the more than 5 years we have been using the software, our experience with Xero has been overwhelmingly positive. The improvements and new features that have been added in that time have been relevant and well implemented$q$,
  $q$For us as a small manufacturing company that exports its products worldwide, Xero has proved to be an excellent fit with our needs. It integrates seamlessly with our bank accounts in multiple currencies, as well as our MRP system. The VAT reporting makes submitting VAT returns a very straightforward process. The product is simple to use and all members of our team are comfortable with it. Overall, it provides a high degree of functionality at a very reasonable price point.$q$,
  $q$My only complaint would have been that tools for visualising your financial data were a little thin on the ground, but the new analytics features seem to have addressed this.$q$,
  NULL,
  NULL,
  $q$2025-12-15$q$,
  10,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Elizabeth W.$q$,
  $q$Finance team$q$,
  NULL,
  $q$Non-Profit Organization Management$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  5,
  5,
  5,
  NULL,
  5,
  $q$Xero: user-friendly and a great tool all round$q$,
  $q$The transition was smooth from our former system and has been very straight forward since we started using it.$q$,
  $q$The option to tailor the system exactly to the needs of our team, the clear and well laid out user interface and the direct connection with the bank accounts, making reconciliations quick and easy. Minimal training was required to get people to the standard needed for basic day to day tasks.$q$,
  $q$Nothing to note! All team members are very happy with this system and are really comfortable using it.$q$,
  NULL,
  NULL,
  $q$2025-06-20$q$,
  3,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Patrick F.$q$,
  $q$IT Consultant$q$,
  NULL,
  $q$Hospital & Health Care$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  1,
  3,
  1,
  1,
  2,
  $q$Used to be good, but Xero no longer cares about supporting their customers$q$,
  $q$I've been a user of Xero for over a decade, and I've always found them to be a good platform. However, recently there have been more and more price hikes, and then this year with very little notice (2 months), decided to remove the very basic functionality of manually entered payrolls. For some users they have an option of changing their payroll provider to one which integrates with their platform, which is awkward mid-year, and incurs additional costs. In other cases, users are in a region where there is no partner payroll provider available! On top of this, _another_ price hike has been announced for the coming months. So in the end, they are raising prices while removing functionality and inconveniencing customers that have been with them for many years. Given the choice between changing accounting platforms or payroll providers, we are looking at getting off Xero, given their increasingly customer-unfriendly practices recently.$q$,
  $q$Xero had been a good, simple platform for our small business for many years, covering our needs at a reasonable cost.$q$,
  $q$In the past few months removed functionality that we and many other users rely on, while at the same time having raised prices with another increase occurring in another few months.$q$,
  NULL,
  NULL,
  $q$2025-07-30$q$,
  24,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Doran P.$q$,
  $q$Owner$q$,
  NULL,
  $q$Health, Wellness and Fitness$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$1-2 years$q$,
  4,
  4,
  3,
  5,
  4,
  $q$Great Accounting Program For Solo Business$q$,
  $q$Overall, I'm happy. I would like to see better pricing for micro businesses and for the banking sync to get worked out.$q$,
  $q$I've been with Xero for 3 years now. Customer service is great. I've had to use them a few times for various things and they always get things handled quickly. The dashboard is easy to use and figure out so was setting up my books. Overall, it's a great product. I like the new budgeting tools and reports are robust. Syncs easily with my Square and Amazon accounts.$q$,
  $q$The constant price increases are tough for me to keep in budget. The bank syncing is clunky. There are full months when I can't import the transactions and then have to enter each one manually. Those months suck.$q$,
  NULL,
  NULL,
  $q$2025-09-12$q$,
  5,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Richey J.$q$,
  $q$General Manager$q$,
  NULL,
  $q$Education Management$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$1-2 years$q$,
  4,
  4,
  3,
  NULL,
  4,
  $q$Generally Great But Still Slightly Pricey$q$,
  $q$Generally really good but maybe needs more flexibility on some payroll features. Just being able to click and submit on rti submissions is great. Invoices and accounts generally decent.$q$,
  $q$Easy to use, well set out and organised, payroll is mostly smooth, invoicing and payment processing is straightforward and easy.$q$,
  $q$Some aspects of payroll aren't equipped for specialist HR requirements. Movement between members of staff in the payroll list can be confusing as it removes them from the list when clicked on the staff member. End of Year requirements are persistent even when all completed. Can be quite expensive compared to other software products. But you need to remember it is taking a lot of left work out of the usual admin which is still a saving.$q$,
  NULL,
  NULL,
  $q$2025-08-24$q$,
  4,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Paul H.$q$,
  $q$Owner$q$,
  NULL,
  $q$Mechanical or Industrial Engineering$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$1-2 years$q$,
  2,
  4,
  3,
  2,
  3,
  $q$Limited capability$q$,
  $q$I really like it however not being able to manage sales orders is a huge issue for my business. You would think this would be a simple fix that would significantly increase the penetration of the product as its the way forward.$q$,
  $q$Good for small businesses. Simple to use any can be used on any device. Modern interface and great reporting. Just wish it could do a little more.$q$,
  $q$However, if you have to manage sales orders you need additional software as you can only raise quotes then invoices. This then creates a whole load of integration issues. The support is not there with either the other supplier who blames Xero or Xero who blame the 3rd party supplier. A minefield.$q$,
  NULL,
  NULL,
  $q$2025-06-25$q$,
  14,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Emma C.$q$,
  $q$Business Support Manager$q$,
  NULL,
  $q$Information Technology and Services$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  5,
  5,
  5,
  3,
  5,
  $q$Xero - user-friendly and intuitive$q$,
  $q$User-friendly and intuitive for people like me, who don't have finance backgrounds. This would always be my go-to accounts software.$q$,
  $q$I'm not an accountant or even a fully trained book-keepter, but I use Xero every day. Having previously used other packages for our accounts, Xero is brilliant in terms of being user friendly and intuitive. I love that it syncs with our bank, our CRM software and the app we use for expenses.$q$,
  $q$If ever I need support, I feel like I'm scrabbling around trying to work out where to go to get it. I would love to have as chat bubble somewhere obvious - as long as it doesn't lead to getting stuck in a BOT loop!$q$,
  NULL,
  NULL,
  $q$2026-03-23$q$,
  5,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Emma B.$q$,
  $q$Financial Controller$q$,
  NULL,
  $q$Non-Profit Organization Management$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Excellent one stop accounting software$q$,
  $q$My overall experience with Xero is extremely positive. It offers everything I need to successfully do the accounting for a non-profit with good safety features, different user profiles and access, and storage.$q$,
  $q$Xero is an excellent cloud-based accounting platform that is easy to use, and offers very good quick and responsive customer support. Its simple, clear dashboard makes everyday accounting tasks—such as invoicing, bank reconciliation, and expense tracking—efficient. It has many different functions and capabilities which speed up reconciling and customisable reports. It is able to integrate with other software and banks. It offers great value for money for all the features it has.$q$,
  $q$Xero can slow down when you have a lot of transactions, but into the hundreds of thousands and it is not too slow that it is unusable, and this is a minor element, and all the pros outweigh this small con.$q$,
  NULL,
  NULL,
  $q$2026-01-25$q$,
  12,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Rishi G.$q$,
  $q$Software Engineer$q$,
  NULL,
  $q$Information Technology and Services$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  3,
  NULL,
  4,
  $q$It may seem silly but I love Xero for the way it works$q$,
  $q$I am glad to be rid of my spreadsheet for billing. I always messed up the formulas on those and they were a pain to keep up with. Every now and again, the expense tracker double charges me after syncing with my bank and I have to go in and delete the duplicate entry manually so I don't confuse myself. Some of the features work better than I would have anticipated for helping me keep all of my business in one place.$q$,
  $q$The phone app is decent for logging my hours when I am waiting for my coffee (which is also nice). Billing customers has been less of a disaster than I had anticipated. I was also pleased that the sync function worked. The calendar helps me track who owes me money and I am just glad I can finally see the dates. I was not expecting the program to be as easy to use as it was for something that deals with numbers.$q$,
  $q$I do dislike how often I get logged out of Xero once I close the tab. Then I have to sit through another annoying OTP code to get back into my account. The reporting features are very basic and there is no ability to really customize them to show more detailed financial information. Xero is way overpriced for what I feel it does, and losing all of my data if I decide to cancel my subscription is terrifying to me.$q$,
  NULL,
  NULL,
  $q$2026-01-25$q$,
  7,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Adrien J.$q$,
  $q$CEO$q$,
  NULL,
  $q$Real Estate$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  1,
  2,
  1,
  2,
  1,
  $q$Bank feed not working as advertised$q$,
  $q$Very poor, we are considering switching to another solution, one that delivers what it advertises it does and with a product team that takes ownership when it falls short.$q$,
  $q$Simplicity and ease of set-up. Problem is product does not work as advertised and Xero does not want to fix.$q$,
  $q$Bank integration does not work as advertised. Information comes truncated. Although they acknowledge the issue, Xero does not want to take ownership of fixing it. In short, they sell something they don't deliver. This is scamming customers.$q$,
  NULL,
  NULL,
  $q$2026-03-09$q$,
  22,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Deborah K.$q$,
  $q$VIrtual Assistant$q$,
  NULL,
  $q$Consumer Services$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  5,
  5,
  5,
  5,
  4,
  $q$User friendly, especially for individuals$q$,
  $q$So far, so good. A lot of helpful articles available and the Help desk is also prompt with responding.$q$,
  $q$It is very user friendly, especially for small self employed businesses! Customer support are prompt in replying.$q$,
  $q$Would be great if there was a Favourites area on the home screen for easy referral to what is incoming/outgoing/owing rather than having to open issued invoices individually. Also would like to be able to label transactions when reconciling, so that instead of deleting lines individually from bank statement import that are personal transaction not related to my business in any way, a label will then just disregard the transaction instead of continually trying to match it with a Xero item code.$q$,
  NULL,
  NULL,
  $q$2026-01-16$q$,
  3,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Verified Reviewer$q$,
  $q$Manager$q$,
  NULL,
  $q$Apparel & Fashion$q$,
  $q$2-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$6-12 months$q$,
  5,
  5,
  4,
  5,
  5,
  $q$Xero is the Best$q$,
  $q$Xero is a fantastic tool and I love how I can manage all of my financial needs. I will be using this for a very long time$q$,
  $q$xero has great customer support, and very easy to use. The features are great and it makes reporting easy$q$,
  $q$I found it a bit pricy for a startup, but it is value for money based on the features it has and that are what every business needs$q$,
  NULL,
  NULL,
  $q$2026-01-19$q$,
  2,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Mahi P.$q$,
  $q$Data Scientist$q$,
  NULL,
  $q$Information Technology and Services$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$1-2 years$q$,
  5,
  5,
  5,
  4,
  5,
  $q$Best Accounting Software for Small Businesses$q$,
  $q$My overall experience with Xero has been fantastic because It simplifies accounting tasks and helps keep everything organized. It is a reliable tool for managing daily finances without any hassle.$q$,
  $q$Xero is extremely easy to use for beginners and that dashboard is very clean and gives a quick overview of my business finances. I really like the reporting features they are detailed and easy to generate and It offers great value for money considering the time it saves on manual work. The features like invoicing and bill tracking are very helpful.$q$,
  $q$Sometimes the customer support takes a bit longer to respond than expected Occasionally and I have faced minor bugs and issues with the bank feed connection but they usually get resolved.$q$,
  NULL,
  NULL,
  $q$2026-01-26$q$,
  5,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Karen G.$q$,
  $q$Administration manager$q$,
  NULL,
  $q$Information Technology and Services$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$1-2 years$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Xero is the accounting go to$q$,
  $q$This is my go to for all my accounting, both in business and personal. It makes budgeting a breeze.$q$,
  $q$Xero is so easy to use, one of the better and more flexible accounting programs. The links to accounts, hub docs, and tax make this a go to for any accounting use$q$,
  $q$Xero is user friendly, so no real cons of note. I honestly have yet to find a fault or anything negative.$q$,
  NULL,
  NULL,
  $q$2025-07-30$q$,
  3,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Sharelle S.$q$,
  $q$Estimator$q$,
  NULL,
  $q$Construction$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  4,
  5,
  5,
  $q$A fresh and vibrant accounting software package$q$,
  $q$For the times i was running a multi-million dollar construction company - to when I branched out into a solo world, Xero was there to hold my hand every step of the way. Faster payments, smoother transactions - hosts of plug-in software to make Xero as unique as your own business. Easy to teach to newbies - fantastic at handling high-level accounting.$q$,
  $q$The sheer beauty of the user experience - it has grown and changed but always maintained a fresh and vibrant look and feel - as easy as apple pie ;-)$q$,
  $q$The subscription cost for lower end users - they don't really do a 'minimal entry' platform that doesn't hurt your pocket if you're having a rough month. Like all platforms, they have to decide which features that users request will be implemented, and that left some users feeling ignored and out in the cold. It just cant be perfect for everyone, but its damn close!$q$,
  NULL,
  NULL,
  $q$2026-04-27$q$,
  12,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Nikki C.$q$,
  $q$permit technician$q$,
  NULL,
  $q$Construction$q$,
  $q$2-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  5,
  5,
  5,
  3,
  4,
  $q$Simple and Efficient Cloud Accounting$q$,
  $q$My overall experience with Xero has been positive. It’s an easy-to-use platform that simplifies accounting tasks like invoicing, bank reconciliation, and expense tracking with strong automation features. It’s especially helpful for keeping finances organized in one place. However, some advanced reporting and customization features can feel limited, and support isn’t always fast, but overall it’s a reliable and efficient accounting tool.$q$,
  $q$What I like most about Xero is its clean, easy-to-use interface and automation features, especially bank reconciliation and invoicing, which save time and make managing finances much more straightforward.$q$,
  $q$What I liked least about Xero is that customer support can be slow and limited, and some advanced features like reporting, payroll, and customization feel less flexible or harder to use than expected.$q$,
  NULL,
  NULL,
  $q$2026-04-27$q$,
  8,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Sam K.$q$,
  $q$Projects Manager$q$,
  NULL,
  $q$Food Production$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$2+ years$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Complete Accounts Package$q$,
  $q$It is a complete accounts package and does everything you could need it to do. It is simple and easily navigable and if there is something you don't know how to do it is often simple to find out how.$q$,
  $q$We have used Xero for several years to do our accounting. We moved over from Sage. What I like about Xero is it is simple. Everything is laid out sensibly and it is easy to navigate. There are access to many different pre-made reports as well as the ability to customise and favourite as well. We have this software linked to our Cybake account and send over invoices from there daily. We also raise invoices within Xero itself. We also use it for bills. I use this everyday and have never encountered an issue. When there is something I don't know how to do i have never needed to contact customer support. I just search online to find the answer quickly.$q$,
  $q$Some of the pre-made reports have very similar names. Which can be confusing at first until you learn them but that is similar to other software we use or have used in the past. Just means sometimes I click a few different ones before I land on the one I want. Not a big issue.$q$,
  NULL,
  NULL,
  $q$2026-04-02$q$,
  9,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Bryce M.$q$,
  $q$Founder$q$,
  NULL,
  $q$Marketing and Advertising$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$Less than 6 months$q$,
  2,
  4,
  2,
  NULL,
  3,
  $q$Xero application fees are a hidden 2.9 - 4.4% fee on when providing a payment gateway for stripe.$q$,
  $q$I feel as if I've been scammed by xero out of 3-4% of my income on top of their monthly fee as a hidden surcharge for doing business using them. I am upset by having to look for an alternative solution in the middle of my work month after stumbling on this and seeing no effort to rectify from xero's side or justification for the fees they're just there without notice, recourse or warning.$q$,
  $q$Payment gateway set up was easy. Initial set up was fairly simple. I like that invoicing customers is simple enough. As a consultant, I found that valuable. The dashboard was complicated though and getting specifically to my customer payments not intuitive.$q$,
  $q$I feel I was cheated by them. They were charging anywhere from 2.92 - 4.42% in "xero application fees" on top of the stripe fees for stripe's payment processing. I only saw these fees once I went into my stripe portal to process a refund after a month. It's not even a standard rate and the variance isn't based on dollar amount, it doesn't make any sense. This means in order to process a client's payment through xero and stripe, I'm paying anywhere from 6-10% in fees with stripe and xero combined. None of these fees were explained up front from Xero's end though stripe's certainly were. Just googling "xero application fees on stripe" I find I'm not the first or even the first dozen to raise this problem and none of the raised responses on their message boards lead to a resolution. I'm now being forced to research another payment portal provider in the middle of the month because I refuse to send this last month's invoices and pay 10% in fees to xero for it. As I look into other applications like quickbooks, they don't charge fees for payment portal, I've gotten no explanation from xero as to why they do. Furthermore, stripe allows payment processing fees to be passed onto the client, this fee is yours as a xero customer whether you like it or not.$q$,
  NULL,
  NULL,
  $q$2026-02-07$q$,
  14,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Verified Reviewer$q$,
  $q$Finance Operations$q$,
  NULL,
  $q$Automotive$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  4,
  5,
  5,
  $q$Xero wins every time!$q$,
  $q$I have used Xero for over 16 years and would still recommend it as the best finance software tool for any business.$q$,
  $q$Xero is simple to use and has a clean interface. They also have a comprehensive knowledge base and community that can answer just about any question. Invoicing is simple and easy to send, there a very very rarely, if any, bugs and the reporting options continue to grow. Everything you need is in Xero.$q$,
  $q$The pricing could be better and it needs some work for companies who deal with multiple currencies (examples: being able to make payments from Xero via batches for other currencies, or when reconciling it doesn't default to AUD)$q$,
  NULL,
  NULL,
  $q$2026-02-12$q$,
  10,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Verified Reviewer$q$,
  $q$CEO$q$,
  NULL,
  $q$Accounting$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Xero is the hero finance tool you need$q$,
  $q$I love this product I use it as a go to financial tool and I love the integration with bill.com. Makes my life way easier$q$,
  $q$Xero is a gamechanger true value for your money. It's easy to use, great customer service that fixes bugs and issues in a timely manner. Love the user interface dashboard and exceptional features$q$,
  $q$I don't really have an negatives with this product. Maybe the price is a bit heavy for startups without investors but for automations etc. Its just like worth it to get$q$,
  NULL,
  NULL,
  $q$2026-01-20$q$,
  6,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Abbey W.$q$,
  $q$owner, founder$q$,
  NULL,
  $q$Retail$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Simple to use and learn and still robust!$q$,
  $q$I've tried a few bookkeeping programs and either they didn't have enough features to be useful or they were so overly bloated, it made it difficult to do basic tasks or get simple reports on the health of my business. Xero threads the needle perfectly, being simple to use and get the information I need while still being robust enough to fill all of my business needs.$q$,
  $q$Xero is very affordable and the learning curve is much lower than other bookkeeping programs. The reporting dashboard gives me the information I actually need and it's a breeze to hook up my accounts.$q$,
  $q$Sometimes my accounts disconnect randomly and it takes a little bit to get them synched up again without missing any transactions or having them appear more than once.$q$,
  NULL,
  NULL,
  $q$2026-01-20$q$,
  3,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Amanda F.$q$,
  $q$Licensed Real Estate Broker$q$,
  NULL,
  $q$Real Estate$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  4,
  4,
  4,
  NULL,
  4,
  $q$Xero in Real-Estate Accounting Processes$q$,
  $q$Automating over 69% of manual accounting procedures such as general ledger, accounts payable and receivables are the key benefits.$q$,
  $q$Accounting tools are essential to all real-estate brokers. I mainly use Xero since it has an iOS mobile application that allows me to streamline online accounting processes from anywhere.$q$,
  $q$However, some features allocated by Xero aren’t robust enough which forces me to integrate with external Apps, for instance inventory management tools.$q$,
  NULL,
  NULL,
  $q$2025-12-21$q$,
  4,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Abi S.$q$,
  $q$Accountant$q$,
  NULL,
  $q$Pharmaceuticals$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$Less than 6 months$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Good product$q$,
  $q$Overall, my experience at Xerox was a solid and valuable one that helped me build a strong foundation in the tech and document solutions industry. On the positive side, I really appreciated the company’s legacy of innovation, the collaborative teams, and the opportunities to work on meaningful projects that directly improved client workflows. The benefits were competitive, there was good access to training and development resources, and in many roles, work-life balance was decent especially with flexible or hybrid options in recent years. I learned a lot about problem solving, customer focus, and navigating large-scale corporate environments, and I made some great professional connections.$q$,
  $q$I really appreciated the strong emphasis on innovation and problem solving at Xerox. The company has a rich history in technology and document management, and I loved being part of teams that were encouraged to find creative solutions for clients whether it was optimizing workflows with multifunction printers or implementing digital transformation projects. The collaborative environment and access to cutting edge tools allowed me to learn a lot and see the direct impact of my work on improving efficiency for businesses. It felt rewarding to work with talented colleagues who were passionate about delivering reliable, high-quality solutions.$q$,
  $q$What I liked least was the pace of change in some areas, particularly the bureaucratic processes that sometimes slowed down decision making and project execution. In a fast evolving tech landscape, waiting for approvals through multiple layers could delay innovation. That said, I understand it’s common in large, established organizations, and it taught me valuable skills in navigating complex structures and advocating effectively for improvements. I’m excited about opportunities where I can bring that experience to a role with even more agility.$q$,
  NULL,
  NULL,
  $q$2026-03-24$q$,
  1,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Verified Reviewer$q$,
  $q$Owner$q$,
  NULL,
  $q$Retail$q$,
  $q$1-10$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Great integrations and automations$q$,
  $q$Great integrations and automations. As someone who doesn't have a book keeping background I do find it quite user friendly.$q$,
  $q$Great integrations and automations. As someone who doesn't have a book keeping background I do find it quite user friendly.$q$,
  $q$Some reporting components are too complicated, but it is improving with recent updates which is great, including the dashboard.$q$,
  NULL,
  NULL,
  $q$2026-03-17$q$,
  2,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Craig B.$q$,
  $q$Managing director$q$,
  NULL,
  $q$Entertainment$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  5,
  5,
  5,
  $q$Makes accounting fun$q$,
  $q$Overall Xero get a big thumbs up from us, it would take a lot to convince us to change software. Very easy to follow and makes accounting mire fun.$q$,
  $q$With accounting going digital, Xero is affordable and user friendly, allows multiple usersvwith various levels of access. Oir accountant is a verified user so we get top notch customer support through them. Endless features allow each individual to approach reporting and reconciliation in whichever way suits them but all lead to the same resaults. The Dashboard can also be customized to suit which information is important to you and allows to you see the important information at a glance.$q$,
  $q$There isnt really anything to dislike, If you don't understans how to report and record your income and expenses i imagine it could be a little daunting. But with initial guidance, it all comes clear very quickly.$q$,
  NULL,
  NULL,
  $q$2025-10-31$q$,
  4,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Sharon T.$q$,
  $q$Managing director$q$,
  NULL,
  $q$Non-Profit Organization Management$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  false,
  NULL,
  $q$Less than 6 months$q$,
  3,
  3,
  3,
  2,
  3,
  $q$Xero is complex$q$,
  $q$It was a cheaper option than other software however i wish i hsd looked further into before signing up . Other business had advised me it was eady to use howrver it has took me so much more time thsn a basic spreadsheet and i just cant get away with it . I have had nunerous times onto customer support screen sharing and an onboarding session and still do not like this$q$,
  $q$There is a lot of customer support available however its not instant and when your completing your account's you need an immediatre response not a call back$q$,
  $q$Its complicated to use and no-one explained you need multiple apps to upload your receipts and bills and pages of uploads banking invoices . I have found it very complex and frustrating$q$,
  NULL,
  NULL,
  $q$2026-04-03$q$,
  5,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Daryl E.$q$,
  $q$Consultant$q$,
  NULL,
  $q$Information Technology and Services$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  1,
  2,
  1,
  1,
  2,
  $q$Xero - Used to be the best accounting package in the world.$q$,
  $q$I dread every new change they announce. If i could move my companies out of Xero (4 companies and one charity) and onto something that looks like what Xero used to be, i'd do it in a heartbeat. I moved them all off MYOB in about 2008, and it doesn't look like MYOB has improved much since then, and there are no others on the horizon that i know of. Its a sad state of affairs for the future of online accounting packages. I'd describe my time with xero as about ten years of honeymoon where it was the best thing since sliced bread. Xero really lead the world in smart accounting and smart UI. I'd describe the rest of my time since then as miserable, much like an abusive relationship. I dread having to make changes to quotes and invoices because bugs in the UI are so common. Just one example; you add a discount to a line item on a quote, lets say $10, and then realise that you put that discount on the wrong line item, so you delete the discount on that line, and put $10 on the next line item down. Now its correct, so you click save, and it won't save. So you change the discount to a percentage that equals $10 - nope, that doesn't let it save. The error message doesn't help - it just says that there was an error and the quote can't be saved. You check your internet connection - that's fine. Eventually you might just delete the quote and re-create it, and its probably going to work. What you don't know, and Xero is in no mood to let you know (and no intention of fixing this - its been there for ~ a year) is that a discount of "" (an empty field, where you deleted the incorrect discount) will prevent the quote from saving. This is an incredibly simple UI bug to fix, its literally just adding [if discount[line]=''; discount[line]=0] to the code - about 40 characters added, but the a holes managing the xero devs haven't managed to assign someone to that bug for about a year. Their helpdesk are told to inform you that you should just enter "0" instead of pressing delete. This is the kind of moronic bugs that happen all the time in Xero, and its due to one thing only; an insistence on only working on things that look good to attract new users (once you have someone subscribed, they will likely be tied in for at least 12 months by the time they realise the horrors that occur), or improve shareholder value. A good example of this is advertising plastered over the interfaces, especially the invoicing module. Many of us have no intention of using Xero's online payment system - our customers just don't want that, they pay by direct credit, but what used to be a short link is now a large banner advertising "get online payments set up", and now it can't be dismissed. Now there's also a 2-line item in the menu advertising Xero's SMS service - another paid thing that we can't remove even if we have no intention of ever using it. I could go on and on about the abuses, but i'm sure you get the point.$q$,
  $q$Previous to the "new invoicing" interface, the user interface and UX was excellent. Value for money used to be excellent, but then the company floated and started pulling shady moves like removing the expenses module and replacing it with a paid version that had less features and a worse UI. Customer support for fixing things that Xero *can* do is pretty good, support for fixing things like bugs, intentionally broken features, and nags/advertising is very very poor.$q$,
  $q$The downhill trajectory of the UI and UX. Every change to the UI brings a couple of good things, and a bag of dicks. Changes used to be for the benefit of the user (you know, the one who is actually paying for the product). Now its for the benefit of the shareholders, and most times makes the UX much worse. Advertising plastered on the UI making the book keeper's job harder than it could be. Features that just don't work when they used to work fine (auto assigning the next ID on an imported invoice is a classic example of something that used to work and now doesn't, and has been promised to be fixed but here we are, 6 years later, and it still hasn't been given any developer time and probably wont.)$q$,
  NULL,
  NULL,
  $q$2025-10-09$q$,
  35,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Brock G.$q$,
  $q$Digital Marketing Manager$q$,
  NULL,
  $q$Telecommunications$q$,
  $q$51-200$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$2+ years$q$,
  5,
  5,
  5,
  4,
  4,
  $q$A Predominant Solution with Seamless Accounting Management.$q$,
  $q$Generally Xero speed is great and has been reliable in streamlining our bookkeeping ,invoicing and reconciliation processes.$q$,
  $q$Xero pricing is extremely attractive and ability to use it from anywhere us a huge plus.Automation kg bank feeds and reconciliation helps to save another of time and reduces errors. Integrates seamlessly with PayPal and bank which makes it easy to handle payments and purchases. Offer real time visibility into financial data .Gives live dashboard for cash flows ,expenses and invoices .$q$,
  $q$Xero has a limited reporting though for anyone who needs standard reports it meets the needs perfectly. For more advanced reports sometimes it require additional data add -ons.$q$,
  NULL,
  NULL,
  $q$2025-09-26$q$,
  5,
  $q$published$q$
),
(
  (SELECT id FROM software WHERE slug = 'xero'),
  $q$Abdul Rehman M.$q$,
  $q$Director$q$,
  NULL,
  $q$Health, Wellness and Fitness$q$,
  $q$11-50$q$,
  $q$South Africa$q$,
  true,
  $q$Verified LinkedIn User$q$,
  $q$6-12 months$q$,
  5,
  5,
  5,
  5,
  5,
  $q$So easy to use but a little outdated looks wise$q$,
  $q$I've been using Xero for six months now and won't be switching at all. The product JUST WORKS and is ideal for UK usage. It has all the correct VAT accounts by default and almost every British accountant has used it so they find it extremely easy to work with for producing business accounts.$q$,
  $q$I've been using Xero for six months now and won't be switching at all. The product JUST WORKS and is ideal for UK usage. It has all the correct VAT accounts by default and almost every British accountant has used it so they find it extremely easy to work with for producing business accounts.$q$,
  NULL,
  NULL,
  NULL,
  $q$2026-05-05$q$,
  1,
  $q$published$q$
);

COMMIT;
